import { JobGameEvent } from './types';

// 魔法輔助職業彩蛋:tier1「藥師」兩分支共用一組(branch填null),分支A(醫生→心理諮商師→
// 老中醫→神醫/華佗再世)+分支B(獸醫→芳療師→針灸師→都市傳說級神醫)從tier2起各自獨立
// 一組,稱號對照 game/combat.ts 的 JOB_TITLES。每組15則(10 common/3 rare/1 epic/
// 1 legendary)。
export const MAGIC_SUPPORT_JOB_EGGS: JobGameEvent[] = [
  // ── 1階:藥師(兩分支共用) ──
  { id: 'job-magicSupport-1-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '數藥丸數到眼花,魔王攻擊反而清楚多了。' },
  { id: 'job-magicSupport-1-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '客人問副作用,我照著仿單一字不漏地背。' },
  { id: 'job-magicSupport-1-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '藥局排隊人潮比打怪隊伍還長。' },
  { id: 'job-magicSupport-1-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '看藥單看到眼花,還是看得比魔王攻略清楚。' },
  { id: 'job-magicSupport-1-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '客人堅持要吃「特效藥」,我只能耐心解釋。' },
  { id: 'job-magicSupport-1-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '藥袋摺得整整齊齊,自己的生活卻亂七八糟。' },
  { id: 'job-magicSupport-1-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '客人問我能不能算便宜點,我只能笑而不答。' },
  { id: 'job-magicSupport-1-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '調劑調到手痠,打怪反而輕鬆許多。' },
  { id: 'job-magicSupport-1-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '值班到深夜,唯一的陪伴是藥架的白色燈光。' },
  { id: 'job-magicSupport-1-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '客人抱怨藥太苦,我說良藥苦口本來就是這樣。' },
  { id: 'job-magicSupport-1-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '常客特地跑來跟我說吃了藥好多了,謝謝我的建議。' },
  { id: 'job-magicSupport-1-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '打工存的錢,終於湊夠買一件像樣的裝備。' },
  { id: 'job-magicSupport-1-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '藥局前輩難得誇我細心,聽了心裡暖暖的。' },
  { id: 'job-magicSupport-1-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '數了無數顆藥丸之後,我才發現,自己遞出去的其實是同一套仿單台詞,講到都能倒背如流。' },
  { id: 'job-magicSupport-1-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: null, tier: 1, payload: '打烊拉下藥局鐵門的那一刻,我看著今天說了兩百次的「飯後吃」,才明白這份心意其實比較像復讀機。' },

  // ── 分支A 2階:醫生 ──
  { id: 'job-magicSupport-A-2-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '門診看到聲音沙啞,魔王攻擊反而讓喉嚨休息一下。' },
  { id: 'job-magicSupport-A-2-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '病患描述症狀天馬行空,我努力抓出重點。' },
  { id: 'job-magicSupport-A-2-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '值班一整晚,早餐午餐晚餐擠在一起吃。' },
  { id: 'job-magicSupport-A-2-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '病歷寫得比魔王攻略還密密麻麻。' },
  { id: 'job-magicSupport-A-2-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '白袍口袋裡塞滿筆跟壓舌板,還有沒吃完的麵包。' },
  { id: 'job-magicSupport-A-2-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '病患半夜掛急診,我從睡夢中彈起。' },
  { id: 'job-magicSupport-A-2-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '解釋病情解釋到自己都快變成另一種語言。' },
  { id: 'job-magicSupport-A-2-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '一診接一診,水杯永遠只喝了一口。' },
  { id: 'job-magicSupport-A-2-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '家屬情緒激動,我還是得先穩住場面。' },
  { id: 'job-magicSupport-A-2-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '下診才發現,自己的午餐早就冷透了。' },
  { id: 'job-magicSupport-A-2-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '病患康復回診,特地帶了水果來道謝。' },
  { id: 'job-magicSupport-A-2-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '深夜成功穩住一位急重症病患,鬆了口氣。' },
  { id: 'job-magicSupport-A-2-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '主治醫師難得稱讚我的診斷很準確。' },
  { id: 'job-magicSupport-A-2-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '看過這麼多診之後,我才發現,自己早就練就一種本事:一邊點頭同理,一邊心算下一個病人還要等多久。' },
  { id: 'job-magicSupport-A-2-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 2, payload: '深夜送走最後一位病患後,我看著自己寫到一半的病歷,才明白這份職業教會我最實用的一課,是字要寫得夠潦草才像醫生。' },

  // ── 分支A 3階:心理諮商師 ──
  { id: 'job-magicSupport-A-3-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '聽個案講心事講到自己都快哭了。' },
  { id: 'job-magicSupport-A-3-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案沉默不語,我耐心地等著他開口。' },
  { id: 'job-magicSupport-A-3-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '一整天聽完各種煩惱,自己的煩惱倒是沒空處理。' },
  { id: 'job-magicSupport-A-3-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案取消預約,我看著空出來的時段苦笑。' },
  { id: 'job-magicSupport-A-3-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '諮商室的面紙盒,補貨速度比裝備補給還快。' },
  { id: 'job-magicSupport-A-3-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案問我懂不懂他的痛苦,我說我盡力理解。' },
  { id: 'job-magicSupport-A-3-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案情緒失控,我還是得保持冷靜的語氣。' },
  { id: 'job-magicSupport-A-3-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '督導會議上被指出盲點,我虛心地筆記下來。' },
  { id: 'job-magicSupport-A-3-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案送來一張小卡,寫著謝謝我願意聽他說話。' },
  { id: 'job-magicSupport-A-3-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '下班後我還是得先整理好自己的情緒才回家。' },
  { id: 'job-magicSupport-A-3-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案走出低潮期,特地回來跟我分享他的好消息。' },
  { id: 'job-magicSupport-A-3-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '個案哭著說謝謝我一直沒有放棄他。' },
  { id: 'job-magicSupport-A-3-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '督導肯定我這次的處理方式,我鬆了口氣。' },
  { id: 'job-magicSupport-A-3-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '聽過這麼多人的心事之後,我才發現,自己下班後最想做的心理諮商,是找人聽我抱怨個案有多難搞。' },
  { id: 'job-magicSupport-A-3-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 3, payload: '送走終於走出陰霾的個案那天,我看著空出來的時段,才明白這份工作最了不起的地方,是連替自己諮商的時間都排不出來。' },

  // ── 分支A 4階:老中醫 ──
  { id: 'job-magicSupport-A-4-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '把脈把到手痠,魔王的脈象倒是簡單多了。' },
  { id: 'job-magicSupport-A-4-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '藥材抓得比裝備配方還精細。' },
  { id: 'job-magicSupport-A-4-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '病患說西醫看不好,抱著最後希望來找我。' },
  { id: 'job-magicSupport-A-4-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '熬藥熬了一整天,藥香比香水還持久。' },
  { id: 'job-magicSupport-A-4-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '看診看到忘記自己也該補補身體。' },
  { id: 'job-magicSupport-A-4-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '病患問我調理要多久,我說緣分到了自然好。' },
  { id: 'job-magicSupport-A-4-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '老藥櫃的抽屜比我的記憶還可靠。' },
  { id: 'job-magicSupport-A-4-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '把脈把出了不少人生的無奈。' },
  { id: 'job-magicSupport-A-4-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '看診收費算得比藥材成本還便宜。' },
  { id: 'job-magicSupport-A-4-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '收工才想起,自己都沒空替自己調理身體。' },
  { id: 'job-magicSupport-A-4-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '調理多年的老病患終於康復,特地包了紅包謝我。' },
  { id: 'job-magicSupport-A-4-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '一位老病患介紹了好幾個新病患給我。' },
  { id: 'job-magicSupport-A-4-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '病患說吃了我開的藥終於睡得著覺,我也跟著安心。' },
  { id: 'job-magicSupport-A-4-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '調理過無數人的身體之後,我才發現,真正難調的不是體質,是每個人都想用一帖藥解決十年的壞習慣。' },
  { id: 'job-magicSupport-A-4-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 4, payload: '看著多年調理的老病患終於健步如飛,他塞給我一箱橘子當謝禮,我才明白,慢慢來的堅持換到的報酬,通常是水果。' },

  // ── 分支A 5階:神醫/華佗再世 ──
  { id: 'job-magicSupport-A-5-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '被稱華佗再世,診間卻還是那間老舊小屋。' },
  { id: 'job-magicSupport-A-5-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '各地病患慕名而來,掛號排到隔壁鄉鎮。' },
  { id: 'job-magicSupport-A-5-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '疑難雜症找上門,我還是得先靜下心診斷。' },
  { id: 'job-magicSupport-A-5-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '記者來採訪神醫傳說,我端出粗茶招待。' },
  { id: 'job-magicSupport-A-5-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '各方名醫來請益,我還是照舊先把脈再說。' },
  { id: 'job-magicSupport-A-5-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '被稱神醫,診金卻收得比一般醫生還親民。' },
  { id: 'job-magicSupport-A-5-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '疑難病患絡繹不絕,我的休息時間也跟著絕跡。' },
  { id: 'job-magicSupport-A-5-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '徒弟問我看診秘訣,我說秘訣就是多年的耐心。' },
  { id: 'job-magicSupport-A-5-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '被封神醫,我還是每天照樣練脈診功夫。' },
  { id: 'job-magicSupport-A-5-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '收工才想起,自己已經好幾年沒好好休過假。' },
  { id: 'job-magicSupport-A-5-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '一位被判定絕症的病患康復回診,激動地跪謝。' },
  { id: 'job-magicSupport-A-5-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '各地醫院請我去會診疑難雜症,終於收入寬裕一點。' },
  { id: 'job-magicSupport-A-5-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '新進學徒眼神裡的認真,讓我想起了當年的自己。' },
  { id: 'job-magicSupport-A-5-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '治好了這麼多疑難雜症之後,我才發現,自己一直信奉的神奇醫術,說穿了就是願意比別人多聽病人講五分鐘的症狀。' },
  { id: 'job-magicSupport-A-5-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'A', tier: 5, payload: '看著曾被判定絕症的病患健康地走出診間,記者又堵在門口要拍照,我才明白,被稱神醫最大的代價,是連買個早餐都要走後門。' },

  // ── 分支B 2階:獸醫 ──
  { id: 'job-magicSupport-B-2-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '被貓抓傷的次數,比被魔王打傷還多。' },
  { id: 'job-magicSupport-B-2-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '狗狗掛急診,我從睡夢中彈起衝去診所。' },
  { id: 'job-magicSupport-B-2-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '飼主比病患本人還緊張,我得先安撫他們的情緒。' },
  { id: 'job-magicSupport-B-2-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '幫兔子剪指甲,比拆解裝備還需要耐心。' },
  { id: 'job-magicSupport-B-2-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '診所排隊的毛小孩,比排隊打怪的隊伍還可愛。' },
  { id: 'job-magicSupport-B-2-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '被鸚鵡咬了一口,魔王攻擊反而溫柔多了。' },
  { id: 'job-magicSupport-B-2-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '手術服上永遠沾著各種動物的毛。' },
  { id: 'job-magicSupport-B-2-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '飼主問我牠會不會好,我只能誠實地說盡力而為。' },
  { id: 'job-magicSupport-B-2-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '一整天下來,身上的抓痕比戰袍的破損還多。' },
  { id: 'job-magicSupport-B-2-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '收工才發現,自己聞起來比動物還像動物。' },
  { id: 'job-magicSupport-B-2-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '救回一隻重傷的小狗,飼主感激地送來自製點心。' },
  { id: 'job-magicSupport-B-2-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '原本怕生的貓咪主動蹭了蹭我的手。' },
  { id: 'job-magicSupport-B-2-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '飼主特地寫感謝卡,說謝謝我這麼有耐心。' },
  { id: 'job-magicSupport-B-2-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '治療過這麼多不會說話的生命之後,我才發現,牠們的眼神比人類誠實,咬我的力道倒是一點都不手軟。' },
  { id: 'job-magicSupport-B-2-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 2, payload: '看著康復的小動物開心地奔向飼主,我低頭看看白袍上還沒洗掉的爪痕,這大概就是這份溫柔的代價。' },

  // ── 分支B 3階:芳療師 ──
  { id: 'job-magicSupport-B-3-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '調精油調到滿手香味,魔王聞了大概會噴嚏連連。' },
  { id: 'job-magicSupport-B-3-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '客人說想放鬆,我按摩到自己的手先痠了。' },
  { id: 'job-magicSupport-B-3-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '精油瓶擺得整整齊齊,自己的心情卻亂糟糟。' },
  { id: 'job-magicSupport-B-3-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '客人在按摩床上睡著,我輕手輕腳地繼續。' },
  { id: 'job-magicSupport-B-3-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '一整天按摩下來,自己的肩頸比誰都僵硬。' },
  { id: 'job-magicSupport-B-3-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '客人問哪種精油助眠,我自己反而失眠許久。' },
  { id: 'job-magicSupport-B-3-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '按摩室的輕音樂,是我這行唯一的背景配樂。' },
  { id: 'job-magicSupport-B-3-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '客人抱怨力道不夠,我默默加重了手勁。' },
  { id: 'job-magicSupport-B-3-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '調香調到自己都快變成行走的香氛。' },
  { id: 'job-magicSupport-B-3-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '收工才想起,自己已經好久沒好好放鬆過。' },
  { id: 'job-magicSupport-B-3-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '客人說按摩完睡了這輩子最安穩的一覺,特地回來指名找我。' },
  { id: 'job-magicSupport-B-3-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '調配出一款客人專屬的香氛,對方感動得眼眶泛紅。' },
  { id: 'job-magicSupport-B-3-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '客人送了一瓶珍貴精油當謝禮。' },
  { id: 'job-magicSupport-B-3-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '調配過無數種香氣之後,我才發現,自己身上永遠有股洗不掉的薰衣草味,連做夢都聞得到。' },
  { id: 'job-magicSupport-B-3-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 3, payload: '看著客人按摩後終於放鬆睡去的臉,我輕手輕腳收拾器材,順便盤算自己的肩頸到底要痠到什麼時候。' },

  // ── 分支B 4階:針灸師 ──
  { id: 'job-magicSupport-B-4-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '下針下得比揮劍還精準。' },
  { id: 'job-magicSupport-B-4-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '病患怕痛怕得要命,我耐心地慢慢下針。' },
  { id: 'job-magicSupport-B-4-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '銀針消毒消到自己都快變成職業病。' },
  { id: 'job-magicSupport-B-4-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '病患扎完針睡著,我輕手輕腳地退到一旁。' },
  { id: 'job-magicSupport-B-4-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '穴道記得比裝備插槽還熟。' },
  { id: 'job-magicSupport-B-4-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '病患問扎針有用嗎,我說有耐心才有用。' },
  { id: 'job-magicSupport-B-4-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '一整天下針下來,自己的手指反而痠了。' },
  { id: 'job-magicSupport-B-4-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '診間排隊排到門口,忙到忘記喝水。' },
  { id: 'job-magicSupport-B-4-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '病患說扎完針比吃藥還有效,我謙虛地笑笑。' },
  { id: 'job-magicSupport-B-4-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '收工才想起,自己的肩頸也早該扎一針了。' },
  { id: 'job-magicSupport-B-4-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '治好多年的老毛病,病患激動得說不出話。' },
  { id: 'job-magicSupport-B-4-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '老病患介紹了好幾個新病患給我。' },
  { id: 'job-magicSupport-B-4-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '病患說扎完針終於睡得安穩,我也跟著安心。' },
  { id: 'job-magicSupport-B-4-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '下過無數次針之後,我才發現,最難的不是找穴位,是說服病人「痠痛感是正常的」而不是我扎錯了。' },
  { id: 'job-magicSupport-B-4-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 4, payload: '看著久病纏身的病患終於能自在行走,我看看自己扎針扎到有點抽筋的手,才明白信任這東西,其實是靠反覆練習換來的。' },

  // ── 分支B 5階:都市傳說級神醫 ──
  { id: 'job-magicSupport-B-5-c01', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '被封都市傳說,診所卻還是那間巷子裡的小屋。' },
  { id: 'job-magicSupport-B-5-c02', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '網路傳言我治好過各種怪病,我自己都笑了。' },
  { id: 'job-magicSupport-B-5-c03', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '各地慕名而來的病患,排隊排到巷口。' },
  { id: 'job-magicSupport-B-5-c04', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '網友發文說我是神醫,底下留言卻在吵位置在哪。' },
  { id: 'job-magicSupport-B-5-c05', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '被說是傳說,收費卻還是佛心價。' },
  { id: 'job-magicSupport-B-5-c06', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '記者堵在診所門口,我從後門溜出去買午餐。' },
  { id: 'job-magicSupport-B-5-c07', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '各種疑難雜症找上門,我還是先泡壺茶定定神。' },
  { id: 'job-magicSupport-B-5-c08', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '被稱傳說級神醫,診間的椅子還是那張舊藤椅。' },
  { id: 'job-magicSupport-B-5-c09', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '徒弟問我傳說是怎麼來的,我說都是病患自己傳出去的。' },
  { id: 'job-magicSupport-B-5-c10', rarity: 'common', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '收工才想起,自己已經好幾年沒能好好逛過夜市。' },
  { id: 'job-magicSupport-B-5-r01', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '一位跑遍各大醫院都查不出病因的病患,終於在我這裡找到答案。' },
  { id: 'job-magicSupport-B-5-r02', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '各地民俗療法界的前輩特地登門交流。' },
  { id: 'job-magicSupport-B-5-r03', rarity: 'rare', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '新來的學徒眼神裡的敬畏,讓我想起初出茅廬的自己。' },
  { id: 'job-magicSupport-B-5-e01', rarity: 'epic', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '治好了這麼多查不出病因的疑難雜症之後,我才發現,自己靠的不是神秘傳說,是願意多花二十分鐘聽病人講完,順便忍住不看時間。' },
  { id: 'job-magicSupport-B-5-l01', rarity: 'legendary', type: 'text', archetype: 'magicSupport', branch: 'B', tier: 5, payload: '看著又一位病患帶著笑容走出診所,記者又想堵我拍照,我才明白,都市傳說終究會過去,但躲記者的體力倒是練得比看診還扎實。' },
];
