import { JobGameEvent } from './types';

// 魔法遠程職業彩蛋:tier1「電競選手/實況主」兩分支共用一組(branch填null),分支A
// (軟體工程師→研究員/科學家→駭客→AI天才工程師)+分支B(資料科學家→量子物理博士生→
// 密碼學專家→諾貝爾獎得主)從tier2起各自獨立一組,稱號對照 game/combat.ts 的 JOB_TITLES。
// 每組15則(10 common/3 rare/1 epic/1 legendary)。
export const MAGIC_RANGED_JOB_EGGS: JobGameEvent[] = [
  // ── 1階:電競選手/實況主(兩分支共用) ──
  { id: 'job-magicRanged-1-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '直播間人數個位數,打怪的熱情倒是滿滿。' },
  { id: 'job-magicRanged-1-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '排位掉分掉到懷疑人生,打怪反而穩定發揮。' },
  { id: 'job-magicRanged-1-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '滑鼠鍵盤敲得比誰都快,手速拿去打怪剛剛好。' },
  { id: 'job-magicRanged-1-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '觀眾說我操作很爛,我說那是刻意放水。' },
  { id: 'job-magicRanged-1-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '熬夜開台,黑眼圈比戰績還亮眼。' },
  { id: 'job-magicRanged-1-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '贊助商還沒找上門,先自己贊助自己打怪。' },
  { id: 'job-magicRanged-1-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '斷線重連的瞬間,比打魔王還讓人心跳加速。' },
  { id: 'job-magicRanged-1-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '家人問我在幹嘛,我說在「練功」。' },
  { id: 'job-magicRanged-1-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '彈幕洗版洗到我都認不出自己說了什麼。' },
  { id: 'job-magicRanged-1-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '設備錢花得比裝備錢還兇。' },
  { id: 'job-magicRanged-1-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '第一次有觀眾送禮物,我興奮地截圖留念。' },
  { id: 'job-magicRanged-1-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '訂閱數終於破百,我對著鏡頭傻笑了好一陣子。' },
  { id: 'job-magicRanged-1-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '意外打出一波精彩操作,彈幕瞬間刷起洗版讚美。' },
  { id: 'job-magicRanged-1-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '熬了無數個夜晚直播之後,我才發現,自己享受的不是輸贏,是深夜還有五個人願意看我對著螢幕自言自語。' },
  { id: 'job-magicRanged-1-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: null, tier: 1, payload: '關掉直播的那一刻看著空蕩的房間,我才明白,那些陌生的暱稱比我現實朋友還熟,但一樣不會幫我倒垃圾。' },

  // ── 分支A 2階:軟體工程師 ──
  { id: 'job-magicRanged-A-2-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '程式碼一行沒寫完,魔王倒是打了好幾隻。' },
  { id: 'job-magicRanged-A-2-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: 'bug 修了一整天,魔王反而比較好對付。' },
  { id: 'job-magicRanged-A-2-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '主管說功能明天要上線,我看著時鐘苦笑。' },
  { id: 'job-magicRanged-A-2-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '咖啡因攝取量比經驗值成長還快。' },
  { id: 'job-magicRanged-A-2-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '會議開了兩小時,結論是「再開一次會」。' },
  { id: 'job-magicRanged-A-2-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '程式一次編譯成功,比打贏魔王還爽。' },
  { id: 'job-magicRanged-A-2-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '加班費算完,還不夠買一件新裝備。' },
  { id: 'job-magicRanged-A-2-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '同事的程式碼寫得比魔王攻略還難懂。' },
  { id: 'job-magicRanged-A-2-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '重構到一半,發現自己也快被重構了。' },
  { id: 'job-magicRanged-A-2-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '收工才發現,自己一整天只跟電腦講過話。' },
  { id: 'job-magicRanged-A-2-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '寫的功能上線後大受好評,主管難得誇了一句。' },
  { id: 'job-magicRanged-A-2-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '找到卡了三天的 bug,爽度堪比打倒魔王。' },
  { id: 'job-magicRanged-A-2-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '意外拿到一筆專案獎金,終於敢買想要的裝備。' },
  { id: 'job-magicRanged-A-2-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '修過無數個 bug 之後,我才發現,自己最擅長的其實是把「五分鐘搞定」的事拖成整晚。' },
  { id: 'job-magicRanged-A-2-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 2, payload: '深夜看著自己寫的程式終於順利運作,我在上面加了行註解「先別動,能跑就好」,然後默默關機睡覺。' },

  // ── 分支A 3階:研究員/科學家 ──
  { id: 'job-magicRanged-A-3-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '實驗數據跑不出來,魔王倒是好打多了。' },
  { id: 'job-magicRanged-A-3-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '論文被審稿人打回來,信心比血條掉得還快。' },
  { id: 'job-magicRanged-A-3-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '實驗室待到半夜,只有儀器陪著我。' },
  { id: 'job-magicRanged-A-3-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '研究經費比裝備維修費還吃緊。' },
  { id: 'job-magicRanged-A-3-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '同儕壓力比打怪還讓人喘不過氣。' },
  { id: 'job-magicRanged-A-3-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '文獻讀到眼花,魔王反而是種放鬆。' },
  { id: 'job-magicRanged-A-3-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '實驗失敗了第十次,我還是決定再試一次。' },
  { id: 'job-magicRanged-A-3-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '研討會報告緊張到手心冒汗。' },
  { id: 'job-magicRanged-A-3-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '咖啡續了第五杯,實驗還沒跑完。' },
  { id: 'job-magicRanged-A-3-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '收工才想起,自己已經好幾天沒曬過太陽。' },
  { id: 'job-magicRanged-A-3-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '論文終於被接受刊登,興奮到睡不著。' },
  { id: 'job-magicRanged-A-3-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '指導教授難得稱讚我的實驗設計很巧妙。' },
  { id: 'job-magicRanged-A-3-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '意外的實驗結果,反而開啟了一個全新的研究方向。' },
  { id: 'job-magicRanged-A-3-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '失敗了無數次實驗之後,我才發現,真正支撐我的不是好奇心,是研究經費已經花下去,不做完不能認賠。' },
  { id: 'job-magicRanged-A-3-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 3, payload: '深夜實驗室終於跑出期待已久的數據,我看看時間凌晨四點,除了自己,沒人會知道這一刻有多值得慶祝。' },

  // ── 分支A 4階:駭客 ──
  { id: 'job-magicRanged-A-4-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '破解防火牆比打魔王還花時間。' },
  { id: 'job-magicRanged-A-4-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '深夜盯著螢幕,眼睛比防護罩還乾。' },
  { id: 'job-magicRanged-A-4-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '委託金入帳,比打贏魔王還讓人安心。' },
  { id: 'job-magicRanged-A-4-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '追查漏洞追到天亮,才發現自己也沒吃晚餐。' },
  { id: 'job-magicRanged-A-4-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '匿名接案,連客戶都不知道我的長相。' },
  { id: 'job-magicRanged-A-4-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '一行程式碼寫錯,整晚的努力瞬間白費。' },
  { id: 'job-magicRanged-A-4-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: 'VPN 開了七層,只是為了訂個外送。' },
  { id: 'job-magicRanged-A-4-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '客戶催進度催得比魔王攻擊還急。' },
  { id: 'job-magicRanged-A-4-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '螢幕的藍光,是我這行唯一的日光浴。' },
  { id: 'job-magicRanged-A-4-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '收工才發現,窗外天都亮了。' },
  { id: 'job-magicRanged-A-4-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '幫一家小公司找出資安漏洞,對方感激地多付了一筆酬勞。' },
  { id: 'job-magicRanged-A-4-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '成功攔截一次詐騙攻擊,默默保護了一群陌生人。' },
  { id: 'job-magicRanged-A-4-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '同行在論壇上匿名稱讚我的技術,我看了會心一笑。' },
  { id: 'job-magicRanged-A-4-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '在暗處守護了這麼多陌生人的資安之後,我才發現,沒人知道我的臉,連客戶都以為我是個團隊。' },
  { id: 'job-magicRanged-A-4-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 4, payload: '成功擋下一次大規模攻擊的那個深夜,我發了封報告就去睡了,新聞隔天說是「原因不明的異常中止」,大概說的就是我。' },

  // ── 分支A 5階:AI天才工程師 ──
  { id: 'job-magicRanged-A-5-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '模型訓練跑了一整晚,魔王倒是打得比較快。' },
  { id: 'job-magicRanged-A-5-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '演算法優化到極致,咖啡杯還是同一個沒洗。' },
  { id: 'job-magicRanged-A-5-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '媒體說我是天才,我看著報錯的程式碼苦笑。' },
  { id: 'job-magicRanged-A-5-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '投資人搶著見面,我卻只想多睡兩小時。' },
  { id: 'job-magicRanged-A-5-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '模型準確率再高,還是有算不準的時候。' },
  { id: 'job-magicRanged-A-5-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '團隊會議討論到深夜,咖啡因是唯一的燃料。' },
  { id: 'job-magicRanged-A-5-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '演講邀約多到行程排不下,論文倒是還沒寫完。' },
  { id: 'job-magicRanged-A-5-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '新聞標題寫著顛覆產業,我盯著崩潰的程式碼苦笑。' },
  { id: 'job-magicRanged-A-5-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '被稱天才工程師,自己心裡清楚都是熬夜熬出來的。' },
  { id: 'job-magicRanged-A-5-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '收工才發現,自己已經好幾天沒好好吃頓飯。' },
  { id: 'job-magicRanged-A-5-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '模型成功解決了一個困擾業界多年的難題,團隊一起歡呼。' },
  { id: 'job-magicRanged-A-5-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '收到一封用戶感謝信,說我的系統真的幫到了他。' },
  { id: 'job-magicRanged-A-5-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '年輕工程師說想成為像我一樣的人,我一時語塞。' },
  { id: 'job-magicRanged-A-5-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '打造出無數個模型之後,我才發現,自己最想解決的問題,其實是為什麼咖啡杯永遠洗不完。' },
  { id: 'job-magicRanged-A-5-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'A', tier: 5, payload: '看著自己打造的系統真的幫助了一個人,我盯著投資人畫的大餅,默默把這句感謝存進真正重要的資料夾。' },

  // ── 分支B 2階:資料科學家 ──
  { id: 'job-magicRanged-B-2-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '數據清理花的時間,比打怪還久十倍。' },
  { id: 'job-magicRanged-B-2-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '模型跑出來的結果,連我自己都嚇一跳。' },
  { id: 'job-magicRanged-B-2-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '主管要的報表,永遠是「今天下班前」。' },
  { id: 'job-magicRanged-B-2-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '圖表畫得漂亮,結論卻沒人想聽。' },
  { id: 'job-magicRanged-B-2-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '咖啡因跟數據量一起爆表。' },
  { id: 'job-magicRanged-B-2-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '模型準確率提升1%,慶祝也只值一杯手搖。' },
  { id: 'job-magicRanged-B-2-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '會議上被問「這數字代表什麼」,我心裡也在問自己。' },
  { id: 'job-magicRanged-B-2-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '程式跑一半當機,重跑一次心都碎了。' },
  { id: 'job-magicRanged-B-2-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '同事說我很會算,我說只是很會算加班時數。' },
  { id: 'job-magicRanged-B-2-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '收工才發現,自己盯螢幕盯到眼睛乾澀。' },
  { id: 'job-magicRanged-B-2-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '分析結果幫公司省下一大筆成本,主管難得請客。' },
  { id: 'job-magicRanged-B-2-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '意外發現數據裡藏著的有趣規律,興奮得睡不著。' },
  { id: 'job-magicRanged-B-2-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '報告受到高層肯定,終於有人記得我的名字。' },
  { id: 'job-magicRanged-B-2-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '清理過無數筆雜亂數據之後,我發現自己的人生格式一樣亂七八糟,只是沒人付錢請我清理。' },
  { id: 'job-magicRanged-B-2-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 2, payload: '深夜看著螢幕上終於乾淨的數據集,我存好檔,才想起明天主管大概又要一份新的報表。' },

  // ── 分支B 3階:量子物理博士生 ──
  { id: 'job-magicRanged-B-3-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '推導公式推到一半,發現前面算錯了。' },
  { id: 'job-magicRanged-B-3-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '指導教授的建議,比魔王攻略還難懂。' },
  { id: 'job-magicRanged-B-3-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '獎學金比零用錢還少,論文卻比裝備還重。' },
  { id: 'job-magicRanged-B-3-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '實驗室的量子儀器,比我的睡眠還珍貴。' },
  { id: 'job-magicRanged-B-3-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '同學問我在研究什麼,我解釋了半天他還是聽不懂。' },
  { id: 'job-magicRanged-B-3-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '畢業遙遙無期,論文進度卻卡在原地。' },
  { id: 'job-magicRanged-B-3-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '深夜的實驗室只剩我跟嗡嗡作響的儀器。' },
  { id: 'job-magicRanged-B-3-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '口試委員的問題,比魔王的攻擊還犀利。' },
  { id: 'job-magicRanged-B-3-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '推導了三天的公式,結果只是白板上的一堆數字。' },
  { id: 'job-magicRanged-B-3-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '收工才發現,自己已經好幾天沒跟人類好好對話。' },
  { id: 'job-magicRanged-B-3-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '意外的實驗結果讓指導教授眼睛一亮。' },
  { id: 'job-magicRanged-B-3-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '論文終於通過口試,那一刻整個人都虛脫了。' },
  { id: 'job-magicRanged-B-3-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '研究成果被國際期刊接受,同學紛紛前來道賀。' },
  { id: 'job-magicRanged-B-3-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '推導了無數次公式之後,我才發現,量子世界的不確定性,比不上我到底哪年才能畢業的不確定性。' },
  { id: 'job-magicRanged-B-3-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 3, payload: '論文口試通過走出會議室的那一刻,我只想到一件事:終於可以睡覺了。' },

  // ── 分支B 4階:密碼學專家 ──
  { id: 'job-magicRanged-B-4-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '破解一組加密演算法,比破解魔王弱點還費神。' },
  { id: 'job-magicRanged-B-4-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '客戶要求的加密強度,比我的荷包安全多了。' },
  { id: 'job-magicRanged-B-4-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '一組密鑰算錯,整個系統重來一次。' },
  { id: 'job-magicRanged-B-4-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '深夜審查程式碼,眼睛比密文還難解。' },
  { id: 'job-magicRanged-B-4-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '會議上滿是專有名詞,連我自己都要想一下。' },
  { id: 'job-magicRanged-B-4-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '客戶催上線,我還在反覆驗證安全性。' },
  { id: 'job-magicRanged-B-4-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '演算法優化到極限,咖啡因也優化到極限。' },
  { id: 'job-magicRanged-B-4-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '同行的論文比魔王攻略還難啃。' },
  { id: 'job-magicRanged-B-4-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '找出一個潛在漏洞,慶祝方式只是喝口冷掉的咖啡。' },
  { id: 'job-magicRanged-B-4-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '收工才發現,窗外天色已經亮了。' },
  { id: 'job-magicRanged-B-4-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '幫金融機構抓出一個致命漏洞,對方感激涕零。' },
  { id: 'job-magicRanged-B-4-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '設計的加密演算法被業界採用,論文引用數也跟著上升。' },
  { id: 'job-magicRanged-B-4-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '收到匿名感謝信,說我保護了無數用戶的隱私。' },
  { id: 'job-magicRanged-B-4-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '守護過無數組密鑰之後,我才發現,自己最擅長守住的秘密,是我到底幾天沒洗頭。' },
  { id: 'job-magicRanged-B-4-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 4, payload: '成功擋下一次針對性攻擊之後,獎金入帳,我才明白,這份沉默的守護,終究還是要靠加班費撐著。' },

  // ── 分支B 5階:諾貝爾獎得主 ──
  { id: 'job-magicRanged-B-5-c01', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '被稱諾貝爾獎得主,水電費帳單還是要自己繳。' },
  { id: 'job-magicRanged-B-5-c02', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '媒體採訪排到滿,實驗室的燈卻常常忘記關。' },
  { id: 'job-magicRanged-B-5-c03', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '得獎感言想了好久,還是覺得寫論文比較拿手。' },
  { id: 'job-magicRanged-B-5-c04', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '各國學術機構邀約不斷,行事曆比魔王攻略還密。' },
  { id: 'job-magicRanged-B-5-c05', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '年輕學者恭敬地請教,我還是先請他坐下喝杯茶。' },
  { id: 'job-magicRanged-B-5-c06', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '獎金入帳的那天,我還是先拿去繳了研究經費。' },
  { id: 'job-magicRanged-B-5-c07', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '記者追問我的成功秘訣,我說其實就是失敗次數比較多。' },
  { id: 'job-magicRanged-B-5-c08', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '被封為傳奇學者,我還是照樣熬夜盯著實驗數據。' },
  { id: 'job-magicRanged-B-5-c09', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '演講邀約多到行事曆爆滿,論文倒是還沒寫完。' },
  { id: 'job-magicRanged-B-5-c10', rarity: 'common', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '收工才想起,自己已經好幾年沒好好休過一次假。' },
  { id: 'job-magicRanged-B-5-r01', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '當年被我指導過的學生,如今也成了獨當一面的研究者,特地回來道謝。' },
  { id: 'job-magicRanged-B-5-r02', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '收到一封素未謀面的年輕人來信,說我的研究改變了他的人生方向。' },
  { id: 'job-magicRanged-B-5-r03', rarity: 'rare', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '新一代學者眼神裡的執著,讓我想起了年輕時的自己。' },
  { id: 'job-magicRanged-B-5-e01', rarity: 'epic', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '拿到這座獎項之後,我才發現,它證明的不是我有多聰明,是我終於有個像樣的理由跟銀行解釋這些年到底在幹嘛。' },
  { id: 'job-magicRanged-B-5-l01', rarity: 'legendary', type: 'text', archetype: 'magicRanged', branch: 'B', tier: 5, payload: '站上頒獎台的那一刻,我盯著台下滿滿的閃光燈,心裡想的卻是實驗室那盞忘記關的燈。' },
];
