import { JobGameEvent } from './types';

// 魔法近戰職業彩蛋:tier1「中二國中生」兩分支共用一組(branch填null),分支A(阿志→
// 道士/法師→命理師→得道仙人)+分支B(八家將小將→乩童→風水師→一代宗師)從tier2起各自
// 獨立一組,稱號對照 game/combat.ts 的 JOB_TITLES。每組15則(10 common/3 rare/
// 1 epic/1 legendary)。
export const MAGIC_MELEE_JOB_EGGS: JobGameEvent[] = [
  // ── 1階:中二國中生(兩分支共用) ──
  { id: 'job-magicMelee-1-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '筆記本邊角畫滿了自創咒語,同學都當我在塗鴉。' },
  { id: 'job-magicMelee-1-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '對著鏡子練習必殺技台詞,被家人聽到超尷尬。' },
  { id: 'job-magicMelee-1-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '段考考砸了,但打怪的直覺倒是滿分。' },
  { id: 'job-magicMelee-1-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '穿著制服打魔王,總覺得自己是隱藏身分的主角。' },
  { id: 'job-magicMelee-1-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '導師說我上課恍神,其實我在腦內模擬戰鬥。' },
  { id: 'job-magicMelee-1-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '零用錢存起來買了一條「有特殊能量」的手鍊。' },
  { id: 'job-magicMelee-1-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '同學說我怪怪的,我說那是「覺醒者」的孤獨。' },
  { id: 'job-magicMelee-1-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '補習班的路上順便繞去打了兩隻怪。' },
  { id: 'job-magicMelee-1-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '家長會通知單塞在書包底,跟打怪的裝備放一起。' },
  { id: 'job-magicMelee-1-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '體育課被選最後一個,打怪倒是從不嫌棄我。' },
  { id: 'job-magicMelee-1-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '同學偷偷問我怎麼變強的,我裝作高深莫測地笑了笑。' },
  { id: 'job-magicMelee-1-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '存夠了零用錢買了一件像樣的裝備,興奮了一整晚。' },
  { id: 'job-magicMelee-1-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '導師難得沒念我,只是笑著說我最近變得不太一樣。' },
  { id: 'job-magicMelee-1-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '在筆記本寫滿中二設定的那些夜晚,我才發現,那其實是我唯一敢做自己的地方。' },
  { id: 'job-magicMelee-1-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: null, tier: 1, payload: '畢業典禮那天翻開寫滿咒語的筆記本,我才明白,曾經的中二,原來是最真心的自己。' },

  // ── 分支A 2階:阿志 ──
  { id: 'job-magicMelee-A-2-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '大家都叫我阿志,連魔王大概都聽過我的名號。' },
  { id: 'job-magicMelee-A-2-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '檳榔攤老闆說我最近氣色不錯,我說是打怪打出來的。' },
  { id: 'job-magicMelee-A-2-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '機車騎得比誰都快,打怪的反應也跟著練出來。' },
  { id: 'job-magicMelee-A-2-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '朋友問我最近在幹嘛,我說「跑江湖」。' },
  { id: 'job-magicMelee-A-2-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '手上的刺青其實是我自己畫的,魔王倒是嚇了一跳。' },
  { id: 'job-magicMelee-A-2-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '陣頭朋友揪我去幫忙,我藉口說要打怪推掉了。' },
  { id: 'job-magicMelee-A-2-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '夜市小吃攤前跟老闆聊了半天,忘記自己是來打怪的。' },
  { id: 'job-magicMelee-A-2-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '朋友都說我講義氣,魔王倒是完全不吃這一套。' },
  { id: 'job-magicMelee-A-2-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '口袋裡的零錢比裝備還輕,但氣勢一定要有。' },
  { id: 'job-magicMelee-A-2-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '街口柑仔店阿姨每次看到我都問打怪打得怎麼樣。' },
  { id: 'job-magicMelee-A-2-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '幫朋友擋了一次麻煩,對方塞給我一包菸表示感謝。' },
  { id: 'job-magicMelee-A-2-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '意外在夜市贏了一次彈珠台,獎品是件不錯的裝備。' },
  { id: 'job-magicMelee-A-2-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '巷口的兄弟說我最近變穩重了,我自己倒是沒發現。' },
  { id: 'job-magicMelee-A-2-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '在江湖上混了這麼久之後,我才發現自己最想守護的,其實是那些跟我一樣沒地方去的朋友。' },
  { id: 'job-magicMelee-A-2-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 2, payload: '深夜騎車回家的路上看著整條熟悉的街,我才明白,這裡才是我唯一想守住的地盤。' },

  // ── 分支A 3階:道士/法師 ──
  { id: 'job-magicMelee-A-3-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '畫符畫到手痠,魔王攻擊倒是輕鬆多了。' },
  { id: 'job-magicMelee-A-3-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '客戶問我改運多少錢,我說先看緣分。' },
  { id: 'job-magicMelee-A-3-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '法器買得比裝備還貴,荷包瞬間見底。' },
  { id: 'job-magicMelee-A-3-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '半夜出勤處理「事情」,回來還得繼續打怪。' },
  { id: 'job-magicMelee-A-3-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '香灰沾了滿身,魔王倒是聞了就跑。' },
  { id: 'job-magicMelee-A-3-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '客戶說我算得很準,其實我也是亂猜的。' },
  { id: 'job-magicMelee-A-3-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '道袍穿久了,打怪都覺得自己在做法事。' },
  { id: 'job-magicMelee-A-3-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '唸咒唸到打結,魔王反而沒被嚇跑。' },
  { id: 'job-magicMelee-A-3-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '收驚收到自己也想被收驚一下。' },
  { id: 'job-magicMelee-A-3-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '客戶送來的謝禮是一箱橘子,比紅包實在多了。' },
  { id: 'job-magicMelee-A-3-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '幫一戶人家安了心,對方硬是包了紅包塞給我。' },
  { id: 'job-magicMelee-A-3-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '半夜的一場法事意外圓滿落幕,自己也鬆了口氣。' },
  { id: 'job-magicMelee-A-3-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '師父難得誇我這次做得不錯,我愣了一下才反應過來。' },
  { id: 'job-magicMelee-A-3-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '做了這麼多場法事之後,我才發現,自己真正在安撫的,其實是每個人心裡的不安。' },
  { id: 'job-magicMelee-A-3-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 3, payload: '深夜送走最後一位求助的人之後,我才明白,這條路走到現在,靠的從來不是法力,是一顆願意留下來的心。' },

  // ── 分支A 4階:命理師 ──
  { id: 'job-magicMelee-A-4-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶問姻緣,我看著自己的行事曆苦笑。' },
  { id: 'job-magicMelee-A-4-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '排八字排到自己都快忘記今天星期幾。' },
  { id: 'job-magicMelee-A-4-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶問我準不準,我說緣分到了自然準。' },
  { id: 'job-magicMelee-A-4-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '算命攤生意好,魔王的攻擊反而沒那麼難算。' },
  { id: 'job-magicMelee-A-4-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶帶著滿肚子煩惱來,我耐心地一條條聽完。' },
  { id: 'job-magicMelee-A-4-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '算盤打得比誰都精,收入卻沒跟著精。' },
  { id: 'job-magicMelee-A-4-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶問流年運勢,我看著自己也還沒轉運苦笑。' },
  { id: 'job-magicMelee-A-4-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '排命盤排到眼睛痠,打怪反而是種休息。' },
  { id: 'job-magicMelee-A-4-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶說我說話很有安定感,我笑說那是練出來的。' },
  { id: 'job-magicMelee-A-4-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '收工才想起,自己都沒空幫自己算一次。' },
  { id: 'job-magicMelee-A-4-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶照著我的建議做了決定,後來特地回來道謝。' },
  { id: 'job-magicMelee-A-4-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '一位老客戶介紹了好幾個新客人給我。' },
  { id: 'job-magicMelee-A-4-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '客戶說聽完我的話心裡踏實多了,我也跟著鬆了口氣。' },
  { id: 'job-magicMelee-A-4-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '幫這麼多人指過路之後,我才發現,自己的人生反而還沒找到真正的方向。' },
  { id: 'job-magicMelee-A-4-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 4, payload: '收攤那晚翻著自己的命盤,我才明白,能陪別人走過迷惘,本身就是一種難得的命格。' },

  // ── 分支A 5階:得道仙人 ──
  { id: 'job-magicMelee-A-5-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '打坐打到魔王都放棄叫我起來打架。' },
  { id: 'job-magicMelee-A-5-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '山中歲月清靜,唯一的煩惱是柴火不夠燒。' },
  { id: 'job-magicMelee-A-5-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '仙風道骨的形象,私底下其實還是很怕蟑螂。' },
  { id: 'job-magicMelee-A-5-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '雲遊四海聽起來瀟灑,其實只是走路走到腳痠。' },
  { id: 'job-magicMelee-A-5-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '道號取得很威風,山下的人卻只記得我本名。' },
  { id: 'job-magicMelee-A-5-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '打怪順便悟道,悟到的道理卻常常忘記。' },
  { id: 'job-magicMelee-A-5-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '山泉水清甜,只是每次挑水都挑到腰痠。' },
  { id: 'job-magicMelee-A-5-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '弟子問我大道理,我其實也還在摸索答案。' },
  { id: 'job-magicMelee-A-5-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '雲霧繚繞的山頭,我只想找個地方曬棉被。' },
  { id: 'job-magicMelee-A-5-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '打坐到一半肚子叫了,仙人也是要吃飯的。' },
  { id: 'job-magicMelee-A-5-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '山下的村民特地上山送來新鮮蔬果,說感謝多年來的庇佑。' },
  { id: 'job-magicMelee-A-5-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '弟子終於學會了一直教不會的心法,我比他還開心。' },
  { id: 'job-magicMelee-A-5-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '意外在山中撿到一顆多年前遺落的珍貴丹藥。' },
  { id: 'job-magicMelee-A-5-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '在山裡修行這麼多年之後,我才發現,得道從來不是遠離塵世,而是學會與自己和平共處。' },
  { id: 'job-magicMelee-A-5-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'A', tier: 5, payload: '望著山下萬家燈火的那個夜晚,我才明白,修了這麼久的道,其實只是為了學會好好活著。' },

  // ── 分支B 2階:八家將小將 ──
  { id: 'job-magicMelee-B-2-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '臉譜畫得比誰都威風,腳步卻還在練。' },
  { id: 'job-magicMelee-B-2-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '踩街踩了一整天,腿比打怪還痠。' },
  { id: 'job-magicMelee-B-2-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '師兄說我步伐亂了,我趕緊重新對齊。' },
  { id: 'job-magicMelee-B-2-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '扛著神將的裝備遊街,比揹裝備還沉。' },
  { id: 'job-magicMelee-B-2-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '練習陣法練到滿身大汗,魔王攻擊倒是輕鬆。' },
  { id: 'job-magicMelee-B-2-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '廟會結束才發現,自己聲音都喊啞了。' },
  { id: 'job-magicMelee-B-2-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '同伴笑我臉譜畫歪了,我尷尬地遮住臉。' },
  { id: 'job-magicMelee-B-2-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '陣頭練習到深夜,鄰居都習慣了鑼鼓聲。' },
  { id: 'job-magicMelee-B-2-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '扮起神將威風凜凜,卸妝後只是個普通少年。' },
  { id: 'job-magicMelee-B-2-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '收工才發現,腳底磨出了好幾個水泡。' },
  { id: 'job-magicMelee-B-2-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '廟會結束,老一輩的師傅難得誇我步伐有樣子了。' },
  { id: 'job-magicMelee-B-2-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '小朋友看到我扮的神將,興奮地拍手叫好。' },
  { id: 'job-magicMelee-B-2-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '意外被選為這次遶境的主力小將,既緊張又驕傲。' },
  { id: 'job-magicMelee-B-2-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '練了這麼久的陣法之後,我才發現,自己早就把這身臉譜背後的責任當成了信仰。' },
  { id: 'job-magicMelee-B-2-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 2, payload: '卸下臉譜的那一刻我才明白,扮演神明的威風不難,守住那份莊重的心才難。' },

  // ── 分支B 3階:乩童 ──
  { id: 'job-magicMelee-B-3-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '起乩前深呼吸一口氣,魔王倒是等得很有耐心。' },
  { id: 'job-magicMelee-B-3-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '信眾排隊問事,隊伍比夜市小吃攤還長。' },
  { id: 'job-magicMelee-B-3-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '乩身結束後全身痠痛,比打完魔王還累。' },
  { id: 'job-magicMelee-B-3-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '廟裡的香火錢,大部分都拿去修廟頂了。' },
  { id: 'job-magicMelee-B-3-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '信眾問前程,我盡力翻譯神明的意思。' },
  { id: 'job-magicMelee-B-3-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '深夜的廟埕安靜得只剩香爐的煙。' },
  { id: 'job-magicMelee-B-3-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '起乩結束才發現自己嗓子完全啞了。' },
  { id: 'job-magicMelee-B-3-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '信眾送來水果謝禮,比紅包實在多了。' },
  { id: 'job-magicMelee-B-3-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '廟公念叨我最近懶散,我還是乖乖去掃廟埕。' },
  { id: 'job-magicMelee-B-3-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '收工才想起,自己一整天都沒吃東西。' },
  { id: 'job-magicMelee-B-3-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '幫一位信眾解開多年的心結,對方哭著跪謝神明,也謝了我。' },
  { id: 'job-magicMelee-B-3-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '一場法事圓滿落幕,廟公難得對我點頭。' },
  { id: 'job-magicMelee-B-3-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '深夜獨自留守廟裡,卻覺得從沒這麼安心過。' },
  { id: 'job-magicMelee-B-3-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '幫這麼多信眾傳達過神明的話之後,我才發現,自己早就分不清是神明借我的口,還是我借神明的名說出了心裡話。' },
  { id: 'job-magicMelee-B-3-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 3, payload: '深夜廟埕只剩我一人打掃的那一刻,我才明白,信仰從來不是神明給的,是自己一步步走出來的。' },

  // ── 分支B 4階:風水師 ──
  { id: 'job-magicMelee-B-4-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '客戶家的格局亂七八糟,我拿著羅盤研究半天。' },
  { id: 'job-magicMelee-B-4-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '看風水看到自己家都還沒整理。' },
  { id: 'job-magicMelee-B-4-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '客戶問我怎麼擺才招財,我看著自己的錢包苦笑。' },
  { id: 'job-magicMelee-B-4-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '爬上屋頂看方位,鄰居還以為我在修屋頂。' },
  { id: 'job-magicMelee-B-4-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '客戶說我講得很玄,我說這其實都是常識。' },
  { id: 'job-magicMelee-B-4-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '羅盤買得比裝備還貴,精準度卻還在練。' },
  { id: 'job-magicMelee-B-4-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '看完一整天的房子,腿比打十場怪還痠。' },
  { id: 'job-magicMelee-B-4-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '客戶堅持要照古法擺設,我只好配合演出。' },
  { id: 'job-magicMelee-B-4-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '收費算得比裝備維修費還便宜。' },
  { id: 'job-magicMelee-B-4-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '收工才想起,自己的房間格局也亂糟糟的。' },
  { id: 'job-magicMelee-B-4-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '客戶照我的建議調整格局後,生意真的變好了,特地回來道謝。' },
  { id: 'job-magicMelee-B-4-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '一位老客戶介紹了好幾個新案子給我。' },
  { id: 'job-magicMelee-B-4-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '客戶說家裡氣氛變好了,連小孩都變得比較安穩。' },
  { id: 'job-magicMelee-B-4-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '看過這麼多人家的風水之後,我才發現,真正決定一個家好不好的,從來不是方位,是住在裡面的人。' },
  { id: 'job-magicMelee-B-4-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 4, payload: '看著客戶一家人終於和睦地圍坐吃飯,我才明白,我改的不是風水,是他們願意重新靠近彼此的心。' },

  // ── 分支B 5階:一代宗師 ──
  { id: 'job-magicMelee-B-5-c01', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '被喊一代宗師,銀行存摺還是一樣單薄。' },
  { id: 'job-magicMelee-B-5-c02', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '弟子成群拜師,學費卻常常打折。' },
  { id: 'job-magicMelee-B-5-c03', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '各方請託不斷,行程比魔王攻略還複雜。' },
  { id: 'job-magicMelee-B-5-c04', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '徒弟問我大道至簡是什麼意思,我自己也還在想。' },
  { id: 'job-magicMelee-B-5-c05', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '名號響亮,家裡還是那間老公寓。' },
  { id: 'job-magicMelee-B-5-c06', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '記者來訪問傳承,我端出泡好的老人茶招待。' },
  { id: 'job-magicMelee-B-5-c07', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '徒弟們爭相模仿我的口頭禪,聽了有點好笑。' },
  { id: 'job-magicMelee-B-5-c08', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '各路人馬來請益,我還是照舊先泡壺茶。' },
  { id: 'job-magicMelee-B-5-c09', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '被稱一代宗師,我還是每天照樣練功。' },
  { id: 'job-magicMelee-B-5-c10', rarity: 'common', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '收徒收到記不住每個人的名字,只好都叫「阿弟」。' },
  { id: 'job-magicMelee-B-5-r01', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '一位當年被我度過的信眾,如今帶著孩子回來謝我。' },
  { id: 'job-magicMelee-B-5-r02', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '各廟宇請我去指導,收入終於稍微寬裕一點。' },
  { id: 'job-magicMelee-B-5-r03', rarity: 'rare', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '新弟子拜師時眼神跟當年的自己一模一樣。' },
  { id: 'job-magicMelee-B-5-e01', rarity: 'epic', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '收了這麼多年的徒弟之後,我才發現,自己傳下去的從來不是招式,是那份不肯放棄的心。' },
  { id: 'job-magicMelee-B-5-l01', rarity: 'legendary', type: 'text', archetype: 'magicMelee', branch: 'B', tier: 5, payload: '看著滿堂徒弟齊聲喊師父的那一刻,我才明白,一代宗師從來不是終點,是把當年的自己好好交接下去。' },
];
