import { JobGameEvent } from './types';

// 物理遠程職業彩蛋:tier1(!hasChosenJob前不會用到,畢業選定職業後才加進反應池)不分分支,
// tier2-5起分支A(計程車司機→警察→職業獵人→狙擊手)/分支B(長途貨運司機→保鑣→特技替身演員
// →傳說槍手)各自獨立敘事線,每組15則(10 common/3 rare/1 epic/1 legendary)。
export const PHYSICAL_RANGED_JOB_EGGS: JobGameEvent[] = [
  // ── tier1 ──
  { id: 'job-physicalRanged-1-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '外送單接不停,打怪的手都快抽筋。' },
  { id: 'job-physicalRanged-1-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '遲到扣評分,魔王倒是從不遲到。' },
  { id: 'job-physicalRanged-1-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '電動車電量見底,勇氣倒是還有一點。' },
  { id: 'job-physicalRanged-1-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '客人備註寫「不要辣」,結果送錯了整份餐。' },
  { id: 'job-physicalRanged-1-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '爬五樓送餐,腿軟到差點認不出自己的膝蓋。' },
  { id: 'job-physicalRanged-1-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '平台演算法比魔王攻略還難懂。' },
  { id: 'job-physicalRanged-1-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '雨天送餐,全身濕透比打輸魔王還狼狽。' },
  { id: 'job-physicalRanged-1-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '準時送達,唯一的獎勵是自己心裡的踏實。' },
  { id: 'job-physicalRanged-1-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '訂單一個接一個,晚餐永遠輪不到自己。' },
  { id: 'job-physicalRanged-1-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '客人給了差評,理由是「外送太快」。' },
  { id: 'job-physicalRanged-1-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '客人多給了小費,說看我送餐送得很拚。' },
  { id: 'job-physicalRanged-1-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '半夜送到一戶亮著燈等我的人家,對方說了聲謝謝辛苦了。' },
  { id: 'job-physicalRanged-1-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '意外撿到路人掉的錢包,原封不動送回去。' },
  { id: 'job-physicalRanged-1-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '我風雨無阻送過最遠的一單,騎到一半才發現,對方訂的只是一杯手搖飲。' },
  { id: 'job-physicalRanged-1-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: null, tier: 1, payload: '那天送完最後一單,看著手機跳出五星好評,我盯著看了很久,這大概是我這禮拜唯一被稱讚的時刻。' },

  // ── tier2 分支A:計程車司機 ──
  { id: 'job-physicalRanged-2A-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '導航說前方塞車,魔王倒是從不塞車。' },
  { id: 'job-physicalRanged-2A-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '乘客問我認不認識路,我說我連自己人生的路都不太認得。' },
  { id: 'job-physicalRanged-2A-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '跳表跳得比我心跳還快。' },
  { id: 'job-physicalRanged-2A-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '深夜載到一個安靜的乘客,比打魔王還讓人緊張。' },
  { id: 'job-physicalRanged-2A-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '油錢漲了,魔王掉的錢倒是沒漲。' },
  { id: 'job-physicalRanged-2A-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '乘客給了五星好評,我這輩子第一次被打這麼高分。' },
  { id: 'job-physicalRanged-2A-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '倒車入庫的技術,拿去閃魔王攻擊也很夠用。' },
  { id: 'job-physicalRanged-2A-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '空車繞了半小時,終於等到一單。' },
  { id: 'job-physicalRanged-2A-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '乘客在後座聊起自己的煩惱,我一邊開車一邊點頭。' },
  { id: 'job-physicalRanged-2A-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '收工才發現,今天繞的路比打怪走的路還遠。' },
  { id: 'job-physicalRanged-2A-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '乘客下車忘了拿行李,追上去還多賺了一句謝謝。' },
  { id: 'job-physicalRanged-2A-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '半夜載到一個哭著的乘客,我什麼都沒問,只把音樂關小聲。' },
  { id: 'job-physicalRanged-2A-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '意外走了一條沒導航過的捷徑,比魔王攻略還難找。' },
  { id: 'job-physicalRanged-2A-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '載過我車的乘客都說有種說不出的安心感,其實只是因為我開得比人生還謹慎。' },
  { id: 'job-physicalRanged-2A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 2, payload: '那趟深夜的最後一單,乘客下車前說了聲謝謝,我愣了兩秒,那大概是今天唯一一句不是抱怨的話。' },

  // ── tier3 分支A:警察 ──
  { id: 'job-physicalRanged-3A-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '巡邏比打怪還累,而且沒有經驗值。' },
  { id: 'job-physicalRanged-3A-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '開單開到手軟,魔王倒是從來不用開單。' },
  { id: 'job-physicalRanged-3A-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '值夜班值到眼神跟殭屍差不多。' },
  { id: 'job-physicalRanged-3A-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '民眾報案說貓卡在樹上,結果我爬樹的技術意外派上用場。' },
  { id: 'job-physicalRanged-3A-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '報告寫得比魔王攻略還多頁。' },
  { id: 'job-physicalRanged-3A-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '路人問路問到我懷疑自己是不是導航。' },
  { id: 'job-physicalRanged-3A-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '同事說我太雞婆,我說反正閒著也是閒著。' },
  { id: 'job-physicalRanged-3A-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '值班室的咖啡難喝,卻是唯一撐得下去的理由。' },
  { id: 'job-physicalRanged-3A-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '巡邏車繞了一圈,發現最可疑的居然是自己的黑眼圈。' },
  { id: 'job-physicalRanged-3A-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '交通指揮到手痠,魔王攻擊倒是輕鬆多了。' },
  { id: 'job-physicalRanged-3A-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '幫走失的小孩找到家人,他媽媽塞了一瓶飲料給我當謝禮。' },
  { id: 'job-physicalRanged-3A-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '深夜巡邏遇到一個徹夜未歸的少年,我只是陪他走到公車站。' },
  { id: 'job-physicalRanged-3A-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '長官說我表現優異,考績卻跟去年一樣。' },
  { id: 'job-physicalRanged-3A-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '聽說我這個轄區,連魔王出沒都要先跟我報備才敢出來。' },
  { id: 'job-physicalRanged-3A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 3, payload: '那晚送走一個哭著說找不到方向的人之後,我填了三張報告才能下班,守護正義的代價,是加班費永遠對不上。' },

  // ── tier4 分支A:職業獵人 ──
  { id: 'job-physicalRanged-4A-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '追蹤獸跡追了一整天,魔王的腳印倒是好認多了。' },
  { id: 'job-physicalRanged-4A-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '山裡沒訊號,倒是意外清靜。' },
  { id: 'job-physicalRanged-4A-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '獵物跑了,晚餐只能靠乾糧。' },
  { id: 'job-physicalRanged-4A-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '揹著獵槍走十公里,體力都給了山路。' },
  { id: 'job-physicalRanged-4A-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '露營帳篷破了個洞,將就一晚。' },
  { id: 'job-physicalRanged-4A-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '山下的委託費算完,還不夠買一雙好靴子。' },
  { id: 'job-physicalRanged-4A-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '看著滿天星星,忽然忘記自己是來打獵的。' },
  { id: 'job-physicalRanged-4A-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '陷阱設了一整晚,抓到的居然是自己的腳。' },
  { id: 'job-physicalRanged-4A-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '同行的獵人說我太安靜,我說山裡話多容易嚇跑獵物。' },
  { id: 'job-physicalRanged-4A-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '下山才發現,揹回來的東西比揹上去的還重。' },
  { id: 'job-physicalRanged-4A-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '意外救了一隻受傷的幼獸,牠舔了舔我的手才跑走。' },
  { id: 'job-physicalRanged-4A-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '在山裡撿到一把生鏽的舊獵刀,刀柄刻著別人的名字。' },
  { id: 'job-physicalRanged-4A-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '委託人多付了一筆錢,說是謝謝我沒有濫殺無辜。' },
  { id: 'job-physicalRanged-4A-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '在山裡待久了,連魔王看到我都會先繞道走。' },
  { id: 'job-physicalRanged-4A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 4, payload: '那次在山頂等到日出,手機還是沒訊號,倒是難得沒人傳訊息來煩我。' },

  // ── tier5 分支A:狙擊手 ──
  { id: 'job-physicalRanged-5A-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '跪著等一整天,魔王才慢悠悠出現。' },
  { id: 'job-physicalRanged-5A-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '風向算得比魔王攻略還精準。' },
  { id: 'job-physicalRanged-5A-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '瞄準鏡裡的世界,比現實安靜多了。' },
  { id: 'job-physicalRanged-5A-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '一動不動趴了三小時,腰比打贏魔王還痠。' },
  { id: 'job-physicalRanged-5A-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '任務完成,唯一的慶祝是喝完最後一口水。' },
  { id: 'job-physicalRanged-5A-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '子彈比薪水還貴,勇者這行真的不好混。' },
  { id: 'job-physicalRanged-5A-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '偽裝服穿一整天,比魔王本人還像草叢。' },
  { id: 'job-physicalRanged-5A-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '呼吸調得比心跳還慢,才敢扣下扳機。' },
  { id: 'job-physicalRanged-5A-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '任務結束撤離時,才發現全身都僵硬了。' },
  { id: 'job-physicalRanged-5A-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '沒人知道我在哪,連魔王大概也不知道。' },
  { id: 'job-physicalRanged-5A-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '這次任務的獎金,終於夠換一副新瞄準鏡。' },
  { id: 'job-physicalRanged-5A-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '趴了整晚只為了確認目標的作息,結果對方比我還早睡。' },
  { id: 'job-physicalRanged-5A-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '同行的新人問我怕不怕孤獨,我說習慣就好。' },
  { id: 'job-physicalRanged-5A-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '我一輩子沒讓任何人看過自己的臉,只留下傳說裡的一擊必中。' },
  { id: 'job-physicalRanged-5A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'A', tier: 5, payload: '扣下最後一次扳機之後我才想到,這行幹久了,存在感全靠傳說撐著,本人早就沒人記得長什麼樣。' },

  // ── tier2 分支B:長途貨運司機 ──
  { id: 'job-physicalRanged-2B-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '長途貨運跑一趟,睡眠時間都留在休息站。' },
  { id: 'job-physicalRanged-2B-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '貨物比我的行李還重,還得小心輕放。' },
  { id: 'job-physicalRanged-2B-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '休息站的咖啡難喝,卻是熬夜開車的救命水。' },
  { id: 'job-physicalRanged-2B-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '收音機放到重播,魔王的攻略倒是還沒重播過。' },
  { id: 'job-physicalRanged-2B-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '過路費算得比運費還精。' },
  { id: 'job-physicalRanged-2B-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '半夜開車,窗外的風景全是黑的,跟人生一樣。' },
  { id: 'job-physicalRanged-2B-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '送貨地址寫錯,多繞了半座城市。' },
  { id: 'job-physicalRanged-2B-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '休息站的泡麵,是長途路上唯一的溫暖。' },
  { id: 'job-physicalRanged-2B-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '貨車儀表板故障燈亮了,心裡的警示燈更早就亮了。' },
  { id: 'job-physicalRanged-2B-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '收工才發現,今天說的話比打怪的次數還少。' },
  { id: 'job-physicalRanged-2B-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '幫路邊拋錨的車主接電,他塞了一瓶飲料給我。' },
  { id: 'job-physicalRanged-2B-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '深夜遇到同行的貨車閃燈打招呼,那一瞬間覺得沒那麼孤單。' },
  { id: 'job-physicalRanged-2B-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '意外走了一條風景很美的舊路,忘記自己是來送貨的。' },
  { id: 'job-physicalRanged-2B-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '我開過的路,大概比地圖畫得還詳細。' },
  { id: 'job-physicalRanged-2B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 2, payload: '那趟跑了一整夜的長途,天亮時看到日出,只覺得眼睛更痠了,風景什麼的等退休再說。' },

  // ── tier3 分支B:保鑣 ──
  { id: 'job-physicalRanged-3B-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '站崗站到腿麻,魔王攻擊反而是種解脫。' },
  { id: 'job-physicalRanged-3B-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '雇主的行程比魔王攻略還難記。' },
  { id: 'job-physicalRanged-3B-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '西裝穿久了,反而比戰袍還悶熱。' },
  { id: 'job-physicalRanged-3B-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '雇主嫌我表情太嚴肅,我說這是專業。' },
  { id: 'job-physicalRanged-3B-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '耳機裡一整天沒動靜,比打魔王還煎熬。' },
  { id: 'job-physicalRanged-3B-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '警覺性練出來了,晚上睡覺都豎著耳朵。' },
  { id: 'job-physicalRanged-3B-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '雇主的行程延誤,我的午餐時間也跟著延誤。' },
  { id: 'job-physicalRanged-3B-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '墨鏡戴一整天,眼睛比心情還累。' },
  { id: 'job-physicalRanged-3B-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '站在人群外圍,比誰都清楚自己不是主角。' },
  { id: 'job-physicalRanged-3B-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '收工才發現,自己一整天沒說過超過十句話。' },
  { id: 'job-physicalRanged-3B-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '雇主難得對我說了聲辛苦了,我愣了兩秒才反應過來。' },
  { id: 'job-physicalRanged-3B-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '擋下一次意外的推搡,雇主事後多給了一筆獎金。' },
  { id: 'job-physicalRanged-3B-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '雇主的孩子畫了一張圖送我,畫的是我站在旁邊的樣子。' },
  { id: 'job-physicalRanged-3B-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '我一站就是一整夜,連魔王經過都不敢驚動我的雇主。' },
  { id: 'job-physicalRanged-3B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 3, payload: '那天雇主終於安全回到家,跟我說了聲辛苦了,轉身就忘記加班費這件事。' },

  // ── tier4 分支B:特技替身演員 ──
  { id: 'job-physicalRanged-4B-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '從高處摔下來的次數,比打魔王被打飛還多。' },
  { id: 'job-physicalRanged-4B-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '化妝師把我畫得慘不忍睹,鏡子前的自己都嚇一跳。' },
  { id: 'job-physicalRanged-4B-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '導演喊NG十次,魔王倒是打一次就過了。' },
  { id: 'job-physicalRanged-4B-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '護具穿了一層又一層,還是摔得鼻青臉腫。' },
  { id: 'job-physicalRanged-4B-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '演員拿走了所有掌聲,我拿走了所有瘀青。' },
  { id: 'job-physicalRanged-4B-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '片酬算完,還不夠付這次的復健費。' },
  { id: 'job-physicalRanged-4B-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '爆破戲拍完,耳朵嗡嗡響了一整天。' },
  { id: 'job-physicalRanged-4B-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '排練摔車動作,現實中連腳踏車都摔得七葷八素。' },
  { id: 'job-physicalRanged-4B-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '銀幕上看起來瀟灑,現場其實痛到說不出話。' },
  { id: 'job-physicalRanged-4B-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '收工才發現,今天沒有人記得問我痛不痛。' },
  { id: 'job-physicalRanged-4B-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '這次的特效鏡頭一次過,導演終於記住了我的名字。' },
  { id: 'job-physicalRanged-4B-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '演員私下謝謝我幫他擋下危險動作,還請了我一頓飯。' },
  { id: 'job-physicalRanged-4B-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '意外接到一個特寫鏡頭,螢幕上第一次露出了我的臉。' },
  { id: 'job-physicalRanged-4B-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '我身上的傷疤,比演員的獎盃還多,片尾名單卻連個名字都排不進去。' },
  { id: 'job-physicalRanged-4B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 4, payload: '那次從高處墜落順利落地,觀眾鼓掌的是演員,我只默默去冰敷。' },

  // ── tier5 分支B:傳說槍手 ──
  { id: 'job-physicalRanged-5B-c01', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '押鏢的路,比打魔王的路線圖還危險。' },
  { id: 'job-physicalRanged-5B-c02', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '委託人開的價碼很高,風險卻更高。' },
  { id: 'job-physicalRanged-5B-c03', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '路上遇到的麻煩,比魔王本人還難纏。' },
  { id: 'job-physicalRanged-5B-c04', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '護送的貨物完好送達,自己倒是傷痕累累。' },
  { id: 'job-physicalRanged-5B-c05', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '名聲響亮,存款卻沒跟著響亮。' },
  { id: 'job-physicalRanged-5B-c06', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '同行說我是傳說,我說傳說也是要吃飯的。' },
  { id: 'job-physicalRanged-5B-c07', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '馬蹄聲比心跳聲還讓人安心。' },
  { id: 'job-physicalRanged-5B-c08', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '風沙滿面地趕路,終於在天黑前送達。' },
  { id: 'job-physicalRanged-5B-c09', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '委託單越接越大,膽子倒是越練越大。' },
  { id: 'job-physicalRanged-5B-c10', rarity: 'common', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '收工才想起,自己已經很久沒為自己趕過路。' },
  { id: 'job-physicalRanged-5B-r01', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '這趟護送的委託人塞了一筆豐厚小費,說是謝謝我一路的沉默陪伴。' },
  { id: 'job-physicalRanged-5B-r02', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '半路遇到打劫,劫匪一看到我的臉就默默讓路。' },
  { id: 'job-physicalRanged-5B-r03', rarity: 'rare', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '同行的新人牛仔問我怕不怕死,我說怕,只是還有事沒做完。' },
  { id: 'job-physicalRanged-5B-e01', rarity: 'epic', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '我從沒失手過一趟委託,只有自己知道那背後磨壞了幾雙靴子。' },
  { id: 'job-physicalRanged-5B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalRanged', branch: 'B', tier: 5, payload: '送完這趟傳說級的委託,酬勞入帳的那刻我才明白,原來所謂傳說,就是換一種方式繼續缺錢。' },
];
