import { JobGameEvent } from './types';

// 物理近戰職業彩蛋:tier1「工讀生」兩分支共用一組(branch填null),分支A(搬運工→
// 工地師傅→消防員→特種部隊)+分支B(拳擊館學員→拳擊教練→職業拳擊手→傳說拳王)從tier2起
// 各自獨立一組,稱號對照 game/combat.ts 的 JOB_TITLES。每組15則(10 common/3 rare/
// 1 epic/1 legendary),呼應整體70/22/7/1的稀有度比例。
export const PHYSICAL_MELEE_JOB_EGGS: JobGameEvent[] = [
  // ── 1階:工讀生(兩分支共用) ──
  { id: 'job-physicalMelee-1-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '打工排班表比打怪行程還難喬。' },
  { id: 'job-physicalMelee-1-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '時薪算完,還是打怪比較划算。' },
  { id: 'job-physicalMelee-1-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '店長說我態度不夠積極,我說我把積極都留給打怪了。' },
  { id: 'job-physicalMelee-1-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '打工滿一個月,才發現自己連自我介紹都沒準備好。' },
  { id: 'job-physicalMelee-1-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '排到大夜班,順便練了一下夜視能力。' },
  { id: 'job-physicalMelee-1-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '同事離職潮又來一波,我還在苦撐。' },
  { id: 'job-physicalMelee-1-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '打工證明拿到手,才知道原來勇者也要有身分證明。' },
  { id: 'job-physicalMelee-1-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '上班打卡遲到三分鐘,扣的錢比打十隻怪還多。' },
  { id: 'job-physicalMelee-1-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '顧客抱怨東抱怨西,魔王反而沒那麼難搞。' },
  { id: 'job-physicalMelee-1-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '打工這行,永遠有做不完的雜事。' },
  { id: 'job-physicalMelee-1-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '意外被誇讚做得不錯,尷尬到不知道怎麼接話。' },
  { id: 'job-physicalMelee-1-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '打工存的錢,終於湊夠買一件像樣的裝備。' },
  { id: 'job-physicalMelee-1-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '同事偷偷塞給我一杯飲料,說辛苦了。' },
  { id: 'job-physicalMelee-1-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '打工打到最後我才發現,自己其實比誰都拚。' },
  { id: 'job-physicalMelee-1-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: null, tier: 1, payload: '那天領到人生第一份薪水單的瞬間,我才明白,長大不過是換一種方式繼續努力而已。' },

  // ── 分支A 2階:搬運工 ──
  { id: 'job-physicalMelee-A-2-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '搬到一半突然覺得,勇者這工作跟搬家工人根本沒兩樣。' },
  { id: 'job-physicalMelee-A-2-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '客戶說「這個很輕」,結果閃到腰的是我。' },
  { id: 'job-physicalMelee-A-2-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '樓梯爬八趟,連打怪的力氣都被搬光了。' },
  { id: 'job-physicalMelee-A-2-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '紙箱寫著「易碎」,裡面裝的居然是石頭。' },
  { id: 'job-physicalMelee-A-2-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '打怪賺的錢,搞不好全拿去貼補搬運費了。' },
  { id: 'job-physicalMelee-A-2-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '今天搬了一台冰箱,順便練了核心肌群。' },
  { id: 'job-physicalMelee-A-2-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '客戶多給了兩百塊小費,比打倒魔王還有成就感。' },
  { id: 'job-physicalMelee-A-2-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '搬完家發現自己力氣比史萊姆還大,勉強安慰自己。' },
  { id: 'job-physicalMelee-A-2-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '貨車司機說我動作太慢,我說我是勇者不是快遞。' },
  { id: 'job-physicalMelee-A-2-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '搬到最後一件才發現,根本是搬錯地址。' },
  { id: 'job-physicalMelee-A-2-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '客戶家的狗一直吠我,我懷疑牠看穿我只是打工仔。' },
  { id: 'job-physicalMelee-A-2-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '搬完貨才發現老闆忘記付錢,勇者的尊嚴值多少錢。' },
  { id: 'job-physicalMelee-A-2-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '意外搬出一箱古董,賣了比打十隻魔王還賺。' },
  { id: 'job-physicalMelee-A-2-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '我搬到一口會說話的箱子,牠說牠也很想休息。' },
  { id: 'job-physicalMelee-A-2-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 2, payload: '那天搬到一件比自己還重的行李,才明白勇者這條路,也不過是換個方式扛東西活下去。' },

  // ── 分支A 3階:工地師傅 ──
  { id: 'job-physicalMelee-A-3-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '工地上的怪物都比我認識的監工好講話。' },
  { id: 'job-physicalMelee-A-3-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '戴著安全帽打魔王,意外地有安全感。' },
  { id: 'job-physicalMelee-A-3-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '工程進度延誤,魔王攻略進度倒是超前。' },
  { id: 'job-physicalMelee-A-3-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '監工念了整個下午,魔王反而沒那麼可怕了。' },
  { id: 'job-physicalMelee-A-3-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '鷹架都比我穩,穩到我都想睡在上面。' },
  { id: 'job-physicalMelee-A-3-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '今天驗收工程,順便驗收了一下自己的耐性。' },
  { id: 'job-physicalMelee-A-3-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '工班說我太拚,我說反正也不會有加班費。' },
  { id: 'job-physicalMelee-A-3-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '灌漿灌到一半,想起還沒打今天的份額。' },
  { id: 'job-physicalMelee-A-3-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '工地便當比魔王掉的裝備還讓人期待。' },
  { id: 'job-physicalMelee-A-3-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '安全帽掉了,腦袋倒是意外清醒。' },
  { id: 'job-physicalMelee-A-3-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '老闆說這層樓要提前完工,跟打魔王一樣都是天方夜譚。' },
  { id: 'job-physicalMelee-A-3-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '工地撿到一張圖紙,畫的居然是打怪路線圖。' },
  { id: 'job-physicalMelee-A-3-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '監工說我進步很多,我懷疑他在說反話。' },
  { id: 'job-physicalMelee-A-3-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '蓋到最後一層樓,我才發現自己蓋的其實是自己的退休金。' },
  { id: 'job-physicalMelee-A-3-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 3, payload: '那棟大樓終於封頂的那天,我才想起,自己好像也很久沒有為誰蓋過什麼了。' },

  // ── 分支A 4階:消防員 ──
  { id: 'job-physicalMelee-A-4-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '火場衝第一,薪水領最後。' },
  { id: 'job-physicalMelee-A-4-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '水柱噴魔王,順便噴醒自己的鬥志。' },
  { id: 'job-physicalMelee-A-4-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '出勤津貼算完,還是覺得打魔王比較划算。' },
  { id: 'job-physicalMelee-A-4-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '消防車開得比逃跑的怪物還快。' },
  { id: 'job-physicalMelee-A-4-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '今天救了一隻貓,牠看起來比我還累。' },
  { id: 'job-physicalMelee-A-4-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '防火衣悶到爆汗,魔王倒是被嚇跑一半。' },
  { id: 'job-physicalMelee-A-4-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '值班室的泡麵,是唯一的救贖。' },
  { id: 'job-physicalMelee-A-4-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '警報一響,勇者魂瞬間覺醒。' },
  { id: 'job-physicalMelee-A-4-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '救援結束才發現,自己也快變成需要被救援的人。' },
  { id: 'job-physicalMelee-A-4-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '同事說我太拚命,我說反正命也不值多少錢。' },
  { id: 'job-physicalMelee-A-4-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '火場裡撿到一枚戒指,主人已經不知道去哪了。' },
  { id: 'job-physicalMelee-A-4-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '隊長說我這次表現特優,獎金卻跟平常一樣少。' },
  { id: 'job-physicalMelee-A-4-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '意外救出一隻會道謝的怪物,牠說牠也只是想活下去。' },
  { id: 'job-physicalMelee-A-4-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '這次出勤,火場裡的每一道門後面都只有更多的門,我苦笑,這才是真正的地獄副本。' },
  { id: 'job-physicalMelee-A-4-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 4, payload: '那場大火撲滅之後,我才發現,自己好像也一直在滅著心裡那把沒人看見的火。' },

  // ── 分支A 5階:特種部隊 ──
  { id: 'job-physicalMelee-A-5-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '任務簡報比打魔王攻略還難懂。' },
  { id: 'job-physicalMelee-A-5-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '突襲成功,獎金卻遲遲沒進帳戶。' },
  { id: 'job-physicalMelee-A-5-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '深夜潛入,順便偷看了一眼魔王的作息表。' },
  { id: 'job-physicalMelee-A-5-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '隊友說我太安靜,我說特種部隊本來就話少。' },
  { id: 'job-physicalMelee-A-5-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '任務結束,唯一的戰利品是滿身泥巴。' },
  { id: 'job-physicalMelee-A-5-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '裝備比薪水還貴,勇者當得心好累。' },
  { id: 'job-physicalMelee-A-5-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '訓練比實戰還累,魔王看了都心疼。' },
  { id: 'job-physicalMelee-A-5-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '夜視鏡壞了,黑暗中打魔王全靠直覺。' },
  { id: 'job-physicalMelee-A-5-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '任務代號很威風,內容其實只是跑腿。' },
  { id: 'job-physicalMelee-A-5-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '撤退訊號響起,才發現根本沒人記得我還在裡面。' },
  { id: 'job-physicalMelee-A-5-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '這次任務目標,居然只是找回長官弄丟的錢包。' },
  { id: 'job-physicalMelee-A-5-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '潛伏三天三夜,結果魔王根本沒出現過。' },
  { id: 'job-physicalMelee-A-5-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '隊上流傳一個傳說,說最強的士兵都是被生活逼出來的。' },
  { id: 'job-physicalMelee-A-5-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '這次最高機密的任務內容,其實只是保護一個不知道自己很重要的普通人。' },
  { id: 'job-physicalMelee-A-5-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'A', tier: 5, payload: '完成這次任務後才明白,真正的敵人,從來都不是魔王,是那個總是不敢喊累的自己。' },

  // ── 分支B 2階:拳擊館學員 ──
  { id: 'job-physicalMelee-B-2-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '打沙包打到忘記,自己才是要打魔王的人。' },
  { id: 'job-physicalMelee-B-2-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '教練說我出拳沒力,我說我把力氣都省給魔王了。' },
  { id: 'job-physicalMelee-B-2-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '跳繩跳到腿軟,魔王看了都想笑。' },
  { id: 'job-physicalMelee-B-2-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '護齒買貴了,牙齒倒是意外保住了。' },
  { id: 'job-physicalMelee-B-2-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '賽前緊張到吃不下,賽後餓到吃三碗飯。' },
  { id: 'job-physicalMelee-B-2-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '陪練費比獎金還多,這筆帳我算不過來。' },
  { id: 'job-physicalMelee-B-2-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '鏡子前練習出拳,順便練習了自信的表情。' },
  { id: 'job-physicalMelee-B-2-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '教練喊加油,魔王大概也希望我加油快點打完。' },
  { id: 'job-physicalMelee-B-2-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '體重過磅那天,連呼吸都要算重量。' },
  { id: 'job-physicalMelee-B-2-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '打完一場,才發現自己比魔王還喘。' },
  { id: 'job-physicalMelee-B-2-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '意外打贏了一場友誼賽,獎品是一顆過期的巧克力。' },
  { id: 'job-physicalMelee-B-2-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '教練說我有天分,我懷疑他對每個人都這樣說。' },
  { id: 'job-physicalMelee-B-2-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '拳館老闆欠薪三個月,魔王倒是每次都準時出現。' },
  { id: 'job-physicalMelee-B-2-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '我每天練到深夜,只為了有一天能贏過鏡子裡的自己。' },
  { id: 'job-physicalMelee-B-2-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 2, payload: '那場友誼賽打完之後我才懂,原來我一直在打的,不是對手,是不甘心的自己。' },

  // ── 分支B 3階:拳擊教練 ──
  { id: 'job-physicalMelee-B-3-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '教學員出拳,順便教自己不要放棄。' },
  { id: 'job-physicalMelee-B-3-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '學員說我很嚴格,我說魔王更嚴格。' },
  { id: 'job-physicalMelee-B-3-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '拳館租金漲了,鬥志倒是沒漲。' },
  { id: 'job-physicalMelee-B-3-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '陪練到一半,忘記自己才是教練。' },
  { id: 'job-physicalMelee-B-3-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '學員進步的速度,比我的薪水漲得還快。' },
  { id: 'job-physicalMelee-B-3-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '訓練菜單排得比魔王攻略還細。' },
  { id: 'job-physicalMelee-B-3-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '護具都是舊的,精神倒是全新的。' },
  { id: 'job-physicalMelee-B-3-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '教練椅子壞了,我說站著教也一樣。' },
  { id: 'job-physicalMelee-B-3-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '學員問我為什麼還在打,我說因為還沒輸夠。' },
  { id: 'job-physicalMelee-B-3-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '訓練結束才發現,自己流的汗比學員還多。' },
  { id: 'job-physicalMelee-B-3-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '帶出一個冠軍學員,獎金卻只夠買一雙新拳套。' },
  { id: 'job-physicalMelee-B-3-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '深夜還在拳館練習,鄰居以為我在跟自己打架。' },
  { id: 'job-physicalMelee-B-3-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '教練生涯最驕傲的一刻,是有學員說想活得像我一樣。' },
  { id: 'job-physicalMelee-B-3-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '退役後我仍每天進拳館,只為了證明自己還沒被打倒。' },
  { id: 'job-physicalMelee-B-3-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 3, payload: '站上擂台邊看著學員出拳的那一刻,我才明白,原來教別人變強,也是自己變強的方式。' },

  // ── 分支B 4階:職業拳擊手 ──
  { id: 'job-physicalMelee-B-4-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '簽約金看起來很多,扣完經紀費就不多了。' },
  { id: 'job-physicalMelee-B-4-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '賽前體重管理,比打魔王還煎熬。' },
  { id: 'job-physicalMelee-B-4-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '對手比魔王還會打嘴砲。' },
  { id: 'job-physicalMelee-B-4-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '打完一場比賽,獎盃比獎金重。' },
  { id: 'job-physicalMelee-B-4-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '媒體訪問問得比魔王的攻擊還兇。' },
  { id: 'job-physicalMelee-B-4-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '訓練基地伙食差,鬥志倒是意外飽滿。' },
  { id: 'job-physicalMelee-B-4-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '拳套簽名版賣得比賽事門票還貴。' },
  { id: 'job-physicalMelee-B-4-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '對戰前一晚睡不著,魔王倒是睡得很好。' },
  { id: 'job-physicalMelee-B-4-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '贏了比賽,慶功宴卻只有一碗泡麵。' },
  { id: 'job-physicalMelee-B-4-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '傷病纏身,還是得站上擂台。' },
  { id: 'job-physicalMelee-B-4-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '這場比賽的獎金,終於夠付上個月的房租。' },
  { id: 'job-physicalMelee-B-4-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '對手賽後跟我說謝謝,說是我讓他想起打拳的初衷。' },
  { id: 'job-physicalMelee-B-4-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '意外簽下代言,代言的居然是止痛藥。' },
  { id: 'job-physicalMelee-B-4-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '每次倒地我都會再站起來,輸贏不重要,不站起來才是真的輸。' },
  { id: 'job-physicalMelee-B-4-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 4, payload: '那場世界冠軍賽打完之後,我才發現,真正的勝利,是還能站著走出擂台。' },

  // ── 分支B 5階:傳說拳王 ──
  { id: 'job-physicalMelee-B-5-c01', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '傳說歸傳說,房租一樣要繳。' },
  { id: 'job-physicalMelee-B-5-c02', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '粉絲喊我拳王,銀行卻只認得存款數字。' },
  { id: 'job-physicalMelee-B-5-c03', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '退休傳言傳了三年,拳套倒是還沒脫下來。' },
  { id: 'job-physicalMelee-B-5-c04', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '挑戰者一個接一個,獎金卻越來越薄。' },
  { id: 'job-physicalMelee-B-5-c05', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '記者問我巔峰感想,我說巔峰只是換個角度看山谷。' },
  { id: 'job-physicalMelee-B-5-c06', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '傳說級的名號,換不到傳說級的薪水。' },
  { id: 'job-physicalMelee-B-5-c07', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '訓練還是照舊,傳說也是要練出來的。' },
  { id: 'job-physicalMelee-B-5-c08', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '有人問我怕不怕輸,我說我更怕不敢打。' },
  { id: 'job-physicalMelee-B-5-c09', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '拳王腰帶重得要命,壓力比腰帶更重。' },
  { id: 'job-physicalMelee-B-5-c10', rarity: 'common', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '每次登場都被說是傳奇,自己倒是覺得只是還沒放棄而已。' },
  { id: 'job-physicalMelee-B-5-r01', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '意外收到一封信,寫信的是曾經被我打敗的對手,謝謝我讓他學會站起來。' },
  { id: 'job-physicalMelee-B-5-r02', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '傳說賽後被問退休計畫,我說計畫就是繼續打下去。' },
  { id: 'job-physicalMelee-B-5-r03', rarity: 'rare', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '有新人挑戰我,眼神跟當年的自己一模一樣。' },
  { id: 'job-physicalMelee-B-5-e01', rarity: 'epic', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '最後一戰前夕,我把腰帶摸了一整晚,發現這東西比想像中還輕。' },
  { id: 'job-physicalMelee-B-5-l01', rarity: 'legendary', type: 'text', archetype: 'physicalMelee', branch: 'B', tier: 5, payload: '站上那個所有人都仰望的位置之後我才懂,傳說從來不是終點,只是換一種孤獨的方式活著。' },
];
