import { JobGameEvent } from './types';

// 物理輔助職業彩蛋:tier1(!hasChosenJob前不會用到,畢業選定職業後才加進反應池)不分分支,
// tier2-5起分支A(超商大夜班店員→餐廳服務生→護理師→急診室護理師)/分支B(空服員→居家照護員
// →物理治療師→國家代表隊防護員)各自獨立敘事線,每組15則(10 common/3 rare/1 epic/1 legendary)。
export const PHYSICAL_SUPPORT_JOB_EGGS: JobGameEvent[] = [
  // ── tier1 ──
  { id: 'job-physicalSupport-1-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '關東煮顧一整天,比顧血條還累。' },
  { id: 'job-physicalSupport-1-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '客人問廁所在哪,我比問路的還熟。' },
  { id: 'job-physicalSupport-1-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '大夜班顧店,順便顧了自己的黑眼圈。' },
  { id: 'job-physicalSupport-1-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '結帳結到手抽筋,魔王攻擊反而比較溫柔。' },
  { id: 'job-physicalSupport-1-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '報廢的關東煮成了今天唯一的晚餐。' },
  { id: 'job-physicalSupport-1-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '客人退貨理由千奇百怪,比魔王的攻擊模式還難猜。' },
  { id: 'job-physicalSupport-1-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '店長交代的雜事,比打怪清單還長。' },
  { id: 'job-physicalSupport-1-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '補貨補到腰痠,順便練了核心。' },
  { id: 'job-physicalSupport-1-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '掃地掃到打烊,才發現時間過得比打怪還快。' },
  { id: 'job-physicalSupport-1-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '收銀機出錯,對帳對到懷疑人生。' },
  { id: 'job-physicalSupport-1-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '常客記得我的名字,還特地跟我打招呼。' },
  { id: 'job-physicalSupport-1-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '幫一個迷路的老太太找到公車站,她塞給我一顆糖。' },
  { id: 'job-physicalSupport-1-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '打工存的錢,終於湊夠買一件像樣的裝備。' },
  { id: 'job-physicalSupport-1-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '值了整晚的大夜班,我才發現,原來自己一直是店裡最晚離開、也最早被忘記加班費的人。' },
  { id: 'job-physicalSupport-1-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: null, tier: 1, payload: '打烊拉下鐵門的那一刻,我盯著打卡鐘,才明白今天的了不起,大概只值一個時薪。' },

  // ── tier2 分支A:餐廳服務生 ──
  { id: 'job-physicalSupport-2A-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '端菜端到手抖,魔王攻擊反而穩多了。' },
  { id: 'job-physicalSupport-2A-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '客人說上錯菜,其實是他自己記錯了。' },
  { id: 'job-physicalSupport-2A-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '尖峰時段跑桌跑到懷疑自己會不會分身術。' },
  { id: 'job-physicalSupport-2A-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '小費算完,還不夠買一件裝備零件。' },
  { id: 'job-physicalSupport-2A-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '客人喊服務生,我一天被喊了一百次。' },
  { id: 'job-physicalSupport-2A-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '打翻一整盤湯,笑著道歉手卻在抖。' },
  { id: 'job-physicalSupport-2A-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '客滿的餐廳比魔王的軍團還壯觀。' },
  { id: 'job-physicalSupport-2A-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '收工才發現,笑臉肌肉比打怪的肌肉還痠。' },
  { id: 'job-physicalSupport-2A-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '客人問菜單問到我都能倒背如流。' },
  { id: 'job-physicalSupport-2A-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '端了一整天的餐盤,晚餐卻只想躺著。' },
  { id: 'job-physicalSupport-2A-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '客人特地留言稱讚我的服務,店長難得笑了。' },
  { id: 'job-physicalSupport-2A-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '幫一桌吵架的情侶緩頰,最後兩人反而請我喝飲料。' },
  { id: 'job-physicalSupport-2A-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '意外拿到整月最高小費,終於敢買想要的裝備。' },
  { id: 'job-physicalSupport-2A-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '跑了一整晚的桌,我記得住每桌客人的笑臉,卻連自己上一餐吃了什麼都想不起來。' },
  { id: 'job-physicalSupport-2A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 2, payload: '打烊後獨自擦著空蕩蕩的桌子,我對著空氣練習下班後要說的第一句話,結果只想到「累…」。' },

  // ── tier3 分支A:護理師 ──
  { id: 'job-physicalSupport-3A-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '量血壓量到懷疑自己血壓比病人還高。' },
  { id: 'job-physicalSupport-3A-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '打針技術練得比揮劍還準。' },
  { id: 'job-physicalSupport-3A-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '交班報告寫得比魔王攻略還詳細。' },
  { id: 'job-physicalSupport-3A-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '病患半夜按鈴,我睡意瞬間全消。' },
  { id: 'job-physicalSupport-3A-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '值班室的泡麵,是唯一的續命方式。' },
  { id: 'job-physicalSupport-3A-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '護理鞋磨壞一雙又一雙。' },
  { id: 'job-physicalSupport-3A-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '家屬情緒激動,我還是得先穩住自己。' },
  { id: 'job-physicalSupport-3A-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '換藥換到手法比打怪還熟練。' },
  { id: 'job-physicalSupport-3A-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '一整天沒喝水,才想起自己也是人。' },
  { id: 'job-physicalSupport-3A-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '下班脫下口罩,臉上的壓痕比戰袍痕跡還深。' },
  { id: 'job-physicalSupport-3A-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '病患出院前緊緊握著我的手道謝。' },
  { id: 'job-physicalSupport-3A-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '深夜陪一個害怕的孩子聊天,直到他安心睡著。' },
  { id: 'job-physicalSupport-3A-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '主管難得稱讚我處理得很好,我愣了一下才反應過來。' },
  { id: 'job-physicalSupport-3A-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '值完一整輪大夜班,我已經記不清上次一覺到天亮是什麼時候,可能是上輩子。' },
  { id: 'job-physicalSupport-3A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 3, payload: '送走康復出院的病患,他說要請我吃飯答謝,我下班後果然只吃了一碗泡麵。' },

  // ── tier4 分支A:健身教練 ──
  { id: 'job-physicalSupport-4A-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '喊學員加油,順便喊給自己聽。' },
  { id: 'job-physicalSupport-4A-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '學員抱怨太累,我說魔王更累人。' },
  { id: 'job-physicalSupport-4A-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '課表排得比魔王攻略還滿。' },
  { id: 'job-physicalSupport-4A-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '示範動作示範到自己也練了一輪。' },
  { id: 'job-physicalSupport-4A-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '學員體脂降了,我的荷包卻沒漲。' },
  { id: 'job-physicalSupport-4A-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '健身房伙食難吃,鬥志倒是意外飽滿。' },
  { id: 'job-physicalSupport-4A-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '學員愛遲到,我倒是每次都準時。' },
  { id: 'job-physicalSupport-4A-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '一天喊了好幾百句加油,聲音都啞了。' },
  { id: 'job-physicalSupport-4A-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '學員練得比我還兇,我在旁邊看得心驚。' },
  { id: 'job-physicalSupport-4A-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '收工才想起,自己已經很久沒有為了自己練過一次。' },
  { id: 'job-physicalSupport-4A-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '學員瘦身成功,眼眶紅著跟我道謝。' },
  { id: 'job-physicalSupport-4A-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '意外接到轉介紹的新學員,終於不用再擔心這個月的業績。' },
  { id: 'job-physicalSupport-4A-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '學員說看到我的努力,自己也想更努力,我愣了一下有點感動。' },
  { id: 'job-physicalSupport-4A-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '喊了無數次加油之後,我才發現,自己比誰都更需要聽到這兩個字,可惜這行沒人喊教練加油。' },
  { id: 'job-physicalSupport-4A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 4, payload: '看著學員完成從沒想過能做到的動作,他感動得哭了,我在心裡盤算這堂課要不要順便推銷續約方案。' },

  // ── tier5 分支A:急診室護理師 ──
  { id: 'job-physicalSupport-5A-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '急診室的警報聲,比魔王的咆哮還讓人清醒。' },
  { id: 'job-physicalSupport-5A-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '分秒必爭的檢傷分類,比打怪還考驗判斷力。' },
  { id: 'job-physicalSupport-5A-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '新人手忙腳亂,我一邊處理一邊指導。' },
  { id: 'job-physicalSupport-5A-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '一整晚沒坐下,魔王倒是坐著等我打。' },
  { id: 'job-physicalSupport-5A-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '值班表排滿整個月,休假是奢侈品。' },
  { id: 'job-physicalSupport-5A-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '家屬情緒崩潰,我還是得先冷靜安撫。' },
  { id: 'job-physicalSupport-5A-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '急救設備推車推得比戰車還熟練。' },
  { id: 'job-physicalSupport-5A-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '交班時累到聲音都在抖,還是把細節交代清楚。' },
  { id: 'job-physicalSupport-5A-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '同仁說我是急診室的定心丸,我笑說只是不敢倒下。' },
  { id: 'job-physicalSupport-5A-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '下班脫下手套,才發現手指已經泡到發皺。' },
  { id: 'job-physicalSupport-5A-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '搶救回一位病患,家屬跪下來謝我,我扶起他們說這是應該的。' },
  { id: 'job-physicalSupport-5A-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '院方頒了張獎狀給我,我笑說命都保住了,獎狀是其次。' },
  { id: 'job-physicalSupport-5A-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '新人問我怎麼撐過這麼多年,我說撐著撐著就習慣了。' },
  { id: 'job-physicalSupport-5A-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '連續搶救好幾條生命之後,我才發現自己早就分不清這是使命,還是單純忘記申請調班。' },
  { id: 'job-physicalSupport-5A-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'A', tier: 5, payload: '深夜終於等到病房安靜下來,我癱在椅子上,才明白這份「使命感」,其實就是忘記自己也需要休息的委婉說法。' },

  // ── tier2 分支B:空服員 ──
  { id: 'job-physicalSupport-2B-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '推餐車推到手痠,魔王攻擊反而輕鬆。' },
  { id: 'job-physicalSupport-2B-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '亂流來襲,我笑著端穩托盤穩住全場。' },
  { id: 'job-physicalSupport-2B-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '時差調不過來,魔王倒是隨時都醒著。' },
  { id: 'job-physicalSupport-2B-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '乘客按鈴不停,我的笑容練得比誰都標準。' },
  { id: 'job-physicalSupport-2B-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '高跟鞋站一整天,腳比打十場怪還痠。' },
  { id: 'job-physicalSupport-2B-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '免稅品賣得再好,業績獎金還是少少的。' },
  { id: 'job-physicalSupport-2B-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '廣播詞唸得比魔王的挑釁台詞還熟。' },
  { id: 'job-physicalSupport-2B-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '長途航班,飛到最後連微笑肌都在抗議。' },
  { id: 'job-physicalSupport-2B-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '安全示範動作做了幾百次,自己都能背下每個手勢。' },
  { id: 'job-physicalSupport-2B-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '落地才發現,行李箱比自己還累。' },
  { id: 'job-physicalSupport-2B-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '乘客特地寫感謝信給公司,提到了我的名字。' },
  { id: 'job-physicalSupport-2B-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '安撫了一個害怕飛行的小孩,他下機前給了我一個擁抱。' },
  { id: 'job-physicalSupport-2B-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '意外升等商務艙服務,體驗了一次不一樣的視野。' },
  { id: 'job-physicalSupport-2B-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '飛遍了世界各地之後,我記得住十幾個機場的免稅店,卻想不起家裡冰箱還剩什麼。' },
  { id: 'job-physicalSupport-2B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 2, payload: '降落後看著滿臉笑容走出機艙的乘客,我在心裡默默計算,這是這個月第幾次沒能睡在自己的床上。' },

  // ── tier3 分支B:居家照護員 ──
  { id: 'job-physicalSupport-3B-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '幫長輩翻身,比舉重還考驗技巧。' },
  { id: 'job-physicalSupport-3B-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '陪長輩聊天聊到自己都能背出他的故事。' },
  { id: 'job-physicalSupport-3B-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '換尿布換得比換裝備還熟練。' },
  { id: 'job-physicalSupport-3B-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '長輩固執不肯吃藥,我得連哄帶騙。' },
  { id: 'job-physicalSupport-3B-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '半夜爬起來照顧長輩,睡眠比打怪還稀缺。' },
  { id: 'job-physicalSupport-3B-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '薪水不高,責任卻重得像扛著一座山。' },
  { id: 'job-physicalSupport-3B-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '長輩把我認成親人,我笑著也不糾正。' },
  { id: 'job-physicalSupport-3B-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '協助復健運動,比陪練還要有耐心。' },
  { id: 'job-physicalSupport-3B-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '一天下來,腰痠背痛比打魔王還真實。' },
  { id: 'job-physicalSupport-3B-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '收工回家才發現,自己比照顧的長輩還累。' },
  { id: 'job-physicalSupport-3B-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '長輩的家人特地包了紅包謝謝我的照顧。' },
  { id: 'job-physicalSupport-3B-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '長輩突然拉著我的手說謝謝有我陪伴,我眼眶一熱。' },
  { id: 'job-physicalSupport-3B-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '意外發現長輩偷偷替我準備了點心。' },
  { id: 'job-physicalSupport-3B-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '照顧了長輩這麼久之後,我才發現自己陪伴他的時間,比陪伴自己家人的時間還多。' },
  { id: 'job-physicalSupport-3B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 3, payload: '送走安詳離世的長輩那天,家屬塞了個紅包謝謝我,我看著封面燙金的「感謝」兩個字,竟比薪資單還有分量。' },

  // ── tier4 分支B:物理治療師 ──
  { id: 'job-physicalSupport-4B-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '幫病患做關節鬆動術,自己的關節倒是先啵啵作響。' },
  { id: 'job-physicalSupport-4B-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '復健療程排得比魔王攻略還細密。' },
  { id: 'job-physicalSupport-4B-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '病患喊痛,我還是得堅持完成療程。' },
  { id: 'job-physicalSupport-4B-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '幫病患按摩到手指抽筋,自己反而沒空喊痛。' },
  { id: 'job-physicalSupport-4B-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '診間排得滿滿,午餐永遠是隨便吃兩口。' },
  { id: 'job-physicalSupport-4B-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '示範動作示範到自己也順便運動了一輪。' },
  { id: 'job-physicalSupport-4B-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '病患進步的幅度,是我這行最大的成就感。' },
  { id: 'job-physicalSupport-4B-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '一天做完好幾個療程,講話都沒力氣了。' },
  { id: 'job-physicalSupport-4B-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '病患抱怨復健太痛,我笑說沒有痛哪來的進步。' },
  { id: 'job-physicalSupport-4B-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '收工才想起,自己的肩膀也很久沒放鬆過。' },
  { id: 'job-physicalSupport-4B-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '病患重新站起來走路那一刻,眼眶跟著我一起紅了。' },
  { id: 'job-physicalSupport-4B-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '意外被轉介紹了好幾個新病患,診所排隊都排到我這來。' },
  { id: 'job-physicalSupport-4B-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '病患送來親手做的卡片謝謝我的耐心。' },
  { id: 'job-physicalSupport-4B-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '幫無數病患重新站起來之後,我才發現,自己的腰倒是一次次彎下去,再也直不太起來。' },
  { id: 'job-physicalSupport-4B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 4, payload: '看著最頑固的病患終於能自己走出診間,他揮手說再也不用來了,我看著空出來的時段,竟有點高興又有點失落。' },

  // ── tier5 分支B:國家代表隊防護員 ──
  { id: 'job-physicalSupport-5B-c01', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '選手賽前的緊張感,比我自己上場還讓人揪心。' },
  { id: 'job-physicalSupport-5B-c02', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '國際賽事的行程,排得比魔王上崗還密集。' },
  { id: 'job-physicalSupport-5B-c03', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '選手受傷的瞬間,我比誰都先衝上場。' },
  { id: 'job-physicalSupport-5B-c04', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '時差還沒調好,又要準備下一場比賽。' },
  { id: 'job-physicalSupport-5B-c05', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '選手拿了獎牌,我在場邊比誰都激動。' },
  { id: 'job-physicalSupport-5B-c06', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '國旗代表隊的裝備箱,比我的行李還重。' },
  { id: 'job-physicalSupport-5B-c07', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '記者只拍選手,沒人記得場邊還有防護員。' },
  { id: 'job-physicalSupport-5B-c08', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '選手賽前緊張到吃不下,我陪著一起餓肚子。' },
  { id: 'job-physicalSupport-5B-c09', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '一整個賽季下來,自己反而比選手還會忍痛。' },
  { id: 'job-physicalSupport-5B-c10', rarity: 'common', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '收工後看著空蕩蕩的選手村,才想起自己也很久沒回過家。' },
  { id: 'job-physicalSupport-5B-r01', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '選手奪牌後第一個擁抱給了我,說沒有你就沒有今天。' },
  { id: 'job-physicalSupport-5B-r02', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '協會頒了一面感謝獎牌給幕後團隊,我笑著收下。' },
  { id: 'job-physicalSupport-5B-r03', rarity: 'rare', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '新進防護員問我怎麼撐過這麼多屆賽事,我說靠的是選手的信任。' },
  { id: 'job-physicalSupport-5B-e01', rarity: 'epic', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '跟著代表隊征戰過無數場國際賽事之後,我才發現,護照上的紀念章比薪資單上的數字還多。' },
  { id: 'job-physicalSupport-5B-l01', rarity: 'legendary', type: 'text', archetype: 'physicalSupport', branch: 'B', tier: 5, payload: '站在頒獎台下看著選手戴上金牌,轉播鏡頭完全沒帶到我,我拍拍手,順便確認一下候補國旗別針還在不在。' },
];
